apiVersion: v2
name: resource-manager
description: A Helm chart for Kubernetes deploying of the Frinx Resource-Manager
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 2.3.1
appVersion: "6.1.0"
maintainers:
  - name: FRINX
    email: services@frinx.io
    url: https://frinx.io
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 14.x.x
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Monitoring to metrics configuration
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/418
