apiVersion: v2
name: resource-manager
description: A Helm chart for Kubernetes deploying of the Frinx Resource-Manager
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.0.0
appVersion: "1.0.4"
maintainers:
  - name: FRINX
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Create resource-manager helm charts
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/134
