apiVersion: v2
name: frinx-frontend
description: A Helm chart for Kubernetes deployment of the Frinx UI
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 3.0.0
appVersion: "1.0.26"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Changed L3VPN_ENABLED variable name
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/166
    - kind: changed
      description: Changed supported appVersion to 1.0.26+
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/166
