apiVersion: v2
name: frinx-frontend
description: A Helm chart for Kubernetes deployment of the Frinx UI
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 4.0.0
appVersion: "6.0.0"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/images: |
    - name: frinx-frontend
      image: frinx/frinx-frontend:6.0.0
    - name: frinx-graphql-proxy
      image: frinx/frinx-graphql-proxy:6.0.0
  artifacthub.io/changes: |
    - kind: changed
      description: Changed ingress configuration
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/345
    - kind: added
      description: Frinx Graphql Proxy setup
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/345
