apiVersion: v2
name: frinx-frontend
description: A Helm chart for Kubernetes deployment of the Frinx UI
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 4.1.0
appVersion: "6.1.0"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/images: |
    - name: frinx-frontend
      image: frinx/frinx-frontend:6.1.0
    - name: frinx-graphql-proxy
      image: frinx/frinx-graphql-proxy:6.1.0
  artifacthub.io/changes: |
    - kind: changed
      description: Environment variables compatible with release 6.1
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/392
