apiVersion: v2
name: frinx-frontend
description: A Helm chart for Kubernetes deployment of the Frinx UI
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.1.1
appVersion: "0.1.2-gamma"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add default value for AUTH_CLIENT_ID env variable
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/27
