apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-topology.fullname" . }}
  labels:
    {{- include "sample-topology.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sample-topology.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sample-topology.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: sample-topology-volume
      #   emptyDir: {}
      # - name: netconf-testtool-volume
        emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sample-topology.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: copy-netconf-device-files
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
          - sh
          - '-c'
          - 'cp -r /sample-topology/* /tmp/sample-topology/'
        volumeMounts:
          - name: sample-topology-volume
            mountPath: /tmp/sample-topology/
      # - name: copy-netconf-testtool-files
      #   image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      #   command:
      #     - sh
      #     - '-c'
      #     - 'cp -r /netconf-testtool/* /tmp/netconf-testtool/'
      #   volumeMounts:
      #     - name: netconf-testtool-volume
      #       mountPath: /tmp/netconf-testtool/
      {{- with .Values.extraInitContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "-c", "{{ .Values.env.RUN_TESTTOOLS }}"]
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
          - name: sample-topology-volume
            mountPath: /sample-topology
          # - name: netconf-testtool-volume
          #   mountPath: /netconf-testtool
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
