{{- if (include "sample-topology.createRepositorySecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-topology.fullname" . }}-repository
  labels:
    {{- include "sample-topology.labels" . | nindent 4 }}
data:
  USERNAME: {{ .Values.externalConfig.auth.username | b64enc }}
  PASSWORD: {{ .Values.externalConfig.auth.password | b64enc }}
{{- end }}
