apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-topology.fullname" . }}
  labels:
    {{- include "sample-topology.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $device := .Values.devices.devicesSpecification }}
    - name: {{ $device.port | quote }}
      port: {{ $device.port }}
      targetPort: {{ $device.port }}
    {{- end }}  
  selector:
    {{- include "sample-topology.selectorLabels" . | nindent 4 }}
