apiVersion: v2
name: uniflow
description: A Helm chart for Kubernetes deploying conductor-server and workflow-proxy
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 3.0.0
appVersion: "1.0.8"
maintainers:
  - name: FRINX
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: elasticsearch.enabled
    name: elasticsearch
    repository: https://helm.elastic.co
    version: 6.8.22
annotations:
  artifacthub.io/images: |
    - name: uniflow-conductor-server
      image: frinx/uniflow-conductor-server:1.0.8
    - name: workflow-proxy
      image: frinx/workflow-proxy:1.0.9
    - name: uniflow-schellar
      image: frinx/uniflow-schellar:1.9.4
  artifacthub.io/changes: |
    - kind: changed
      description: Change the naming convention for images to match helm standard
      links:
        - name: Renovate docs
          url: https://docs.renovatebot.com/modules/manager/helm-values/
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/52
