apiVersion: v1
kind: ConfigMap
metadata:
  name: frinx-grafana-datasources
data:
  datasource.yml: |
    apiVersion: 1
    datasources:      
      - name: {{ .Values.datasources.influxdb2.name }}
        type: influxdb
        access: proxy
        url:  {{ .Values.datasources.influxdb2.url }}
        basicAuth:  {{ .Values.datasources.influxdb2.basicAuth }}
        basicAuthUser:  {{ .Values.datasources.influxdb2.basicAuthUser }}
        jsonData:
          defaultBucket:  {{ .Values.datasources.influxdb2.defaultBucket }}
          httpMode:  {{ .Values.datasources.influxdb2.httpMode }}
          organization:  {{ .Values.datasources.influxdb2.organization }}
          version: Flux
        secureJsonData:
          basicAuthPassword: {{ .Values.datasources.influxdb2.basicAuthPassword }}
          token: {{ .Values.datasources.influxdb2.token }}
      - name: {{ .Values.datasources.loki.name }}
        type: loki
        access: proxy
        url: {{ .Values.datasources.loki.url }}
        jsonData:
