# Use the python:3.12-alpine3.20 image as the base image
FROM python:3.12-alpine3.20

# Ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# Install pyyaml
RUN set -eux; \
    pip3 install pyyaml==5.4.1 --no-cache-dir

# Command to run the script with the required parameters
#CMD ["/bin/sh", "-c", "pip3 install pyyaml --no-cache-dir && python3 /app/formatter.py /tmp/{{ $value.fetch.file }} /tmp/{{ $value.fetch.file }} /app/filter/config.yaml"]

CMD ["python3"]
