# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts/
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - elastic=https://helm.elastic.co
  - frinx=https://FRINXio.github.io/helm-charts
  - traefik=https://helm.traefik.io/traefik
helm-extra-args: --timeout 600s
excluded-charts:
  - demo-workflows
  - frinx-frontend
  - frinx-grafana-configs
  - inventory
  - krakend
  - sample-topology
  - uniconfig
  - uniflow
  - uniresource
  - worker
