# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - frinx=https://FRINXio.github.io/helm-charts
  - bitnami=https://charts.bitnami.com/bitnami
  - traefik=https://helm.traefik.io/traefik
  - arango=https://arangodb.github.io/kube-arangodb
  - cloudnative-pg=https://cloudnative-pg.github.io/charts