apiVersion: v2
name: frinx-arango-config
version: 2.0.0
description: A Helm chart for Kubernetes deployment of the Arango CRD and ArangoDB configuration files
type: application
home: https://github.com/FRINXio/helm-charts
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
appVersion: "3.9.1"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Move resources to arangodb_config
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/277
    - kind: added
      description: Add option to specify securityContext 
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/277
