arangodb_config:
  image:
    repository: arangodb/arangodb
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  tokenSecretName: arangodb-jwt
  bearerSecretName: arangodb-bearer
  token: 6647ee8a9129b388eabc6c788697197e0fd805346b4867a5d117f0c691c6bfc1
  bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmFuZ29kYiIsInNlcnZlcl9pZCI6ImZvbyJ9.OxGlpYQYzOysECGkonaEP8d64UH1wQeo_XxeIqK8Vgg

arango_operator_secret:
  username: frinx
  password: frinx
