name: null
imageName: "ghcr.io/cloudnative-pg/postgresql:12.10@sha256:3cd378bf6b4e6bdc495cf478ca893a3490ecdab5332a614d99d2adb41b1e63ce"
imagePullPolicy: IfNotPresent
imagePullSecrets: []
instances: 3
primaryUpdateStrategy: "unsupervised"
primaryUpdateMethod: "switchover"
startDelay: 30
stopDelay: 30

replicationSlots: {}
  # ReplicationSlotsConfiguration encapsulates the configuration of replication slots
  # https://cloudnative-pg.io/documentation/1.18/api_reference/#replicationslotsconfiguration

storage:
  # StorageConfiguration is the configuration of the storage of the PostgreSQL instances
  # https://cloudnative-pg.io/documentation/1.18/api_reference/#storageconfiguration
  size: "1Gi"
  # storageClass: 'default'
  # resizeInUseVolumes: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

postgresql: {}
  # PostgresConfiguration defines the PostgreSQL configuration
  # https://cloudnative-pg.io/documentation/1.18/api_reference/#postgresconfiguration
  # parameters:
  #   max_connections: 300
  #   shared_buffers: 256MB
  # pg_hba:
  #   - host all all 10.244.0.0/16 md5

bootstrap:
  initdb:
    database: frinx
    owner: frinx
    secret:
      name: frinx-user
    postInitSQL: {}
    postInitTemplateSQL: {}
    postInitApplicationSQL: {}
    postInitApplicationSQLRefs:
      configMapRefs: {}
      secretRefs: {}

backup: {}
  # BackupConfiguration defines how the backup of the cluster are taken.
  # Currently the only supported backup method is barmanObjectStore.
  # For details and examples refer to the Backup and Recovery section of the documentation
  # https://cloudnative-pg.io/documentation/1.18/api_reference/#backupconfiguration

superuserSecret:
  name: frinx-superuser

monitoring: {}
  # MonitoringConfiguration is the type containing all the monitoring configuration for a certain cluster
  # https://cloudnative-pg.io/documentation/1.18/api_reference/#MonitoringConfiguration

env: {}

envFrom: {}

logLevel: "info"

affinity: {}
  # AffinityConfiguration contains the info we need to create the affinity rules for Pods
  # https://cloudnative-pg.io/documentation/1.18/api_reference/#AffinityConfiguration

secrets:
  superuserSecret:
    name: frinx-superuser
    username: postgres
    password: postgres
  userSecret:
    name: frinx-user
    username: frinx
    password: postgres
  postInitSqlSecret: {}
    # name: post-init-sql-secret
    # sql: |-
    #   CREATE SCHEMA inventory AUTHORIZATION inventory;
