name: null
# -- Image repository with tag
imageName: "ghcr.io/cloudnative-pg/postgresql:12.18"
# -- Image pull policy
imagePullPolicy: IfNotPresent
# -- [Image Pull Secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
imagePullSecrets: []
# -- Number of instances
instances: 2
# -- Primary update strategy configuration
primaryUpdateStrategy: "unsupervised"
# -- Primary update method configuration
primaryUpdateMethod: "switchover"
# -- Start delay configuration
startDelay: 30
# -- Stop delay configuration
stopDelay: 30

# -- [ReplicationSlots] Defines encapsulation of the configuration of replication slots
replicationSlots: {}

# -- [StorageConfiguration] Defines PostgreSQL instances storage configuration https://cloudnative-pg.io/documentation/1.18/api_reference/#storageconfiguration
storage:
  size: "1Gi"
  # storageClass: 'default'
  resizeInUseVolumes: true

# -- [Container resources](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/)
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- [PostgresConfiguration] Defines the PostgreSQL configuration https://cloudnative-pg.io/documentation/1.18/api_reference/#postgresconfiguration
postgresql:
  parameters:
    max_connections: '300'
  #   shared_buffers: 256MB
  # pg_hba:
  #   - host all all 10.244.0.0/16 md5

# -- Bootstrap configuration of cluster
bootstrap:
  initdb:
    database: frinx
    owner: frinx
    # secret:
    #   name: frinx-user
    postInitSQL: {}
    postInitTemplateSQL: {}
    postInitApplicationSQL: {}
    postInitApplicationSQLRefs:
      # extraConfigMapRefs holds a list of references to configmaps
      # key-value format
      extraConfigMapRefs: {}
      # extraSecretRefs holds a list of references to secrets
      # key-value format
      extraSecretRefs: {}
      # secretRefs:
      #   - name: cloud-native-pq-post-init-sql-secret
      #     key: secret.sql

# -- [Backup] Cluster backup configuration https://cloudnative-pg.io/documentation/1.18/api_reference/#backupconfiguration
backup: {}

# -- Podmonitor configuration
monitoring:
  podMonitorEnabled: false

# -- Environmental variables configuration
env: {}

# -- Environmental variables passed from referenced objects
envFrom: {}

# -- Logging level configuration
logLevel: "info"

# -- [Affinity] Defines info about creating affinity rules for pods https://cloudnative-pg.io/documentation/1.18/api_reference/#AffinityConfiguration
affinity: {}

# -- Secrets configuration
secrets:
  superuserSecret:
    existingSecret:
    username: postgres
    password: postgres
  userSecret:
    existingSecret:
    username: frinx
    password: frinx
  postInitSqlSecret:
    # existingSecret:
    # sql: |-
    #   CREATE SCHEMA inventory AUTHORIZATION inventory;
