apiVersion: v2
name: sample-topology
description: A Helm chart for the Frinx Machine sample-topology Kubernetes deployment
type: application
version: 1.0.0
appVersion: "1.9"
maintainers:
  - name: FRINX