apiVersion: v2
name: sample-topology
description: A Helm chart for the Frinx Machine sample-topology Kubernetes deployment
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 3.0.0
appVersion: "6.0.0"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Changed ingress configuration
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/347
