apiVersion: v2
name: sample-topology
description: A Helm chart for the Frinx Machine sample-topology Kubernetes deployment
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.1.0
appVersion: "1.9"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Specify DOCKER_GWBRIDGE_IP address
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/34
