apiVersion: v2
name: sample-topology
description: A Helm chart for the Frinx Machine sample-topology Kubernetes deployment
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 2.0.0
appVersion: "3.0.0"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: Removed unused env and service values
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/291
    - kind: changed
      description: Changed supported version of sample-topology to 3.0.0
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/291
    - kind: changed
      description: Enable just IOS device testtool in sample-topology
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/291
    - kind: added
      description: Add option to specify devices and externalConfig
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/291
