apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uniflow.fullname" . }}-config
data:
  {{- range $key, $value := .Values.configScripts }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
