apiVersion: v2
name: conductor
description: A Helm chart for Kubernetes deploying conductor-server and workflow-proxy
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.0.0
appVersion: "1.0.5"
maintainers:
  - name: FRINX
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://cetic.github.io/helm-charts
    version: 0.2.3
  - condition: elasticsearch.enabled
    name: elasticsearch
    repository: https://helm.elastic.co
    version: 6.8.22
