# Default values for conductor and proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # use the image below to use dynomite, logs, metrics
  # (requires dynomite, fluentd, elastic, others)
  name: frinx/uniflow-conductor-server
  # set to "Always" because using "latest" tag
  # https://github.com/kubernetes/kubernetes/issues/47775
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imageProxy:
  name: frinx/workflow-proxy
  # set to "Always" because using "latest" tag
  # https://github.com/kubernetes/kubernetes/issues/47775
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  CONFIG_PROP: config.properties
  _JAVA_OPTIONS: -Xmx2g
  LOG4J_PROP: log4j.properties
  ELASTIC_URL: elasticsearch-master-headless:9200
  ELASTIC_CLUSTER_HEALTH_COLOR: yellow
  SCHELLAR_TARGET: http://schellar:3000
  SPRING_DATASOURCE_URL:
  SPRING_DATASOURCE_USERNAME:
  SPRING_DATASOURCE_PASSWORD:
  CONDUCTOR_EXTERNAL_PAYLOAD_STORAGE_POSTGRES_URL:
  CONDUCTOR_EXTERNAL_PAYLOAD_STORAGE_POSTGRES_USERNAME:
  CONDUCTOR_EXTERNAL_PAYLOAD_STORAGE_POSTGRES_PASSWORD:

imagePullSecrets:
  - name: artifactory
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: workflow-proxy
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8088
  portWorkers: 8089
  portSchellar: 8087
  portConductor: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
resourcesProxy: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configScripts:
  config.properties: |
    {{- .Files.Get "configs/config.properties" }}
  log4j.properties: |
    {{ .Files.Get "configs/log4j.properties" }}
