apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uniconfig.fullname" . }}-configmap-lighty-uniconfig-config
data:
{{- if .Values.unistoreMode }}
{{- (.Files.Glob "config/lighty-unistore-config.json").AsConfig | nindent 2 }}
{{- else }}
{{- (.Files.Glob "config/lighty-uniconfig-config.json").AsConfig | nindent 2 }}
{{- end }}