apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uniconfig.fullname" . }}
  labels:
    {{- include "uniconfig.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "uniconfig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.alwaysRollAfterUpgrade }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uniconfig.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: uniconfig-frinx-volume
          emptyDir: {}
        {{- if .Values.azure.AKS.enabled }}
        - name: frinx-uniconfig-controller-cache
          azureFile:
            secretName: {{ include "uniconfig.storageSecretName" . }}
            shareName: {{ .Values.uniconfigCacheFolderPath }}
            readOnly: false
        {{- else}}
        {{- if .Values.uniconfigCacheFolderPath }}
        - name: frinx-uniconfig-controller-cache
          hostPath:
            path: {{ .Values.uniconfigCacheFolderPath }}
        {{- end }}
        {{- end }}
        - name: frinx-uniconfig-controller-logs
          emptyDir: {}
        - name: uniconfig-script
          configMap:
            name: {{ include "uniconfig.scriptConfigMapName" . }}
            defaultMode: 0777
            items:
            - key: run_uniconfig.sh
              path: run_uniconfig.sh
        - name: logback
          configMap:
            name: {{ include "uniconfig.logbackConfigMapName" . }}
            defaultMode: 0777
            items:
            - key: logback.xml
              path: logback.xml
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uniconfig.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{ if .Values.dbPersistence.connection_databaseLocations_host }}
        - name: check-db-ready
          image: postgres:alpine
          command: ['sh', '-c',
            "until pg_isready -h {{ .Values.dbPersistence.connection_databaseLocations_host }} -p 5432 -U {{ .Values.dbPersistence.connection_username }};
            do echo waiting for database; sleep 2; done;"]
      {{ else }}
        - name: check-db-ready
          image: postgres:alpine
          command: ['sh', '-c',
            "until pg_isready -h {{ .Release.Name }}-postgresql -p 5432 -U {{ .Values.dbPersistence.connection_username }};
            do echo waiting for database; sleep 2; done;"]
      {{ end }}
        - name: copy-config-files
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - '-c'
            - 'cp -r /opt/uniconfig-frinx/* /tmp/uniconfig-frinx/'
          volumeMounts:
            - name: uniconfig-frinx-volume
              mountPath: /tmp/uniconfig-frinx/
        {{ if .Values.cacheImage.enabled }}
        - name: copy-uniconfig-cache
          image: {{ .Values.cacheImage.repository }}:{{ .Values.cacheImage.tag }}
          securityContext:
            runAsUser: 0  # Run as root, since default user in the source image might not have access to the volume
          command:
            - sh
            - '-c'
            - 'cp -rp {{ .Values.cacheImage.cachePath }} /tmp/uniconfig-frinx/cache && chmod -R 777 /tmp/uniconfig-frinx/cache'
          volumeMounts:
            - name: uniconfig-frinx-volume
              mountPath: /tmp/uniconfig-frinx/
        {{ end }}
        {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.uniconfigCacheFolderPath }}
          command: ["/bin/sh","-c"]
          args: ["/opt/uniconfig-frinx/run_uniconfig.sh"]
          {{- end }}
          env:
            - name: CONTAINER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: {{ .Values.serviceName | quote }}
            - name: PROXY_ENABLED
              value: {{ .Values.proxy.enabled | quote }}
            - name: HTTP_PROXY
              value: {{ .Values.proxy.http_proxy | quote }}
            - name: HTTPS_PROXY
              value: {{ .Values.proxy.https_proxy | quote }}
            - name: NO_PROXY
              value: {{ .Values.proxy.no_proxy | quote }}
            - name: JAVA_MAX_MEM
              value: {{ .Values.java.max_mem | quote }}
            # - name: _JAVA_OPTIONS
              # value: "-Xmx$(JAVA_MAX_MEM) -XX:+AlwaysPreTouch -Djna.nosys=true -XX:+AlwaysPreTouch -Djna.nosys=true -XX:+CrashOnOutOfMemoryError -XX:MaxGCPauseMillis=200 -Xlog:gc:/opt/uniconfig-frinx/log/$(SERVICE_NAME)/$(CONTAINER_ID)/gc.log:tags,time,uptime,level:filecount=10,filesize=5M -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1"
              # value: " --add-opens java.base/java.lang=ALL-UNNAMED -Xmx$(JAVA_MAX_MEM) -cp ${JAR_DIRS} ${MAIN_CLASS} --spring.config.location=${CONFIG} $@"
              {{- if and (eq .Values.postgresql.enabled true) (not .Values.dbPersistence.connection_databaseLocations_host) }}
            - name: DBPERSISTENCE_CONNECTION_DATABASELOCATIONS_0_HOST
              value: "{{ .Release.Name }}-postgresql"
              {{ else }}
            - name: DBPERSISTENCE_CONNECTION_DATABASELOCATIONS_0_HOST
              value: {{ .Values.dbPersistence.connection_databaseLocations_host }}
              {{ end }}
            - name: DBPERSISTENCE_CONNECTION_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniconfig.secretName" . }}
                  key: DBPERSISTENCE_CONNECTION_USERNAME
            - name: DBPERSISTENCE_CONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniconfig.secretName" . }}
                  key: DBPERSISTENCE_CONNECTION_PASSWORD
            - name: DBPERSISTENCE_CONNECTION_SSLPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniconfig.secretName" . }}
                  key: DBPERSISTENCE_CONNECTION_SSLPASSWORD
            - name: CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniconfig.secretName" . }}
                  key: CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD
            - name: TLS_KEYSTOREPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uniconfig.secretName" . }}
                  key: TLS_KEYSTOREPASSWORD
          {{- range $key, $val := .Values.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
          volumeMounts:
          - name: frinx-uniconfig-controller-logs
            mountPath: /opt/uniconfig-frinx/log
          - name: uniconfig-frinx-volume
            mountPath: /opt/uniconfig-frinx
          {{- if .Values.uniconfigCacheFolderPath }}
          - name: frinx-uniconfig-controller-cache
            mountPath: {{ .Values.mountCachePath }}
          {{- end}}
          - name: uniconfig-script
            mountPath: /opt/uniconfig-frinx/run_uniconfig.sh
            subPath: run_uniconfig.sh
          - name: logback
            mountPath: /opt/uniconfig-frinx/config/logback.xml
            subPath: logback.xml
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - 'curl --insecure -o /dev/null --silent --write-out "%{http_code}" -X POST localhost:8181/rests/operations/uniconfig-manager:health -H "Content-Type:application/json"'
            initialDelaySeconds: 60
            timeoutSeconds: 35
            failureThreshold: 20
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - 'curl --insecure -o /dev/null --silent --write-out "%{http_code}" -X POST localhost:8181/rests/operations/uniconfig-manager:health -H "Content-Type:application/json"'
            initialDelaySeconds: 60
            timeoutSeconds: 35
            failureThreshold: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
