apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
    name: regcred
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: common/regcred
      property: .dockerconfigjson
