{{- if .Values.traefikExtraService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.traefikExtraService.name }}
spec:
  type: ClusterIP
  selector:
    {{- include "uniconfig.selectorLabelsForTraefik" . | nindent 4 }}
  ports:
  - port: 8181
    name: uniconfig
    targetPort: "uniconfig"
    protocol: TCP
  - port: 80
    name: web
    targetPort: "web"
    protocol: TCP
  - port: 443
    name: websecure
    targetPort: "websecure"
    protocol: TCP
{{- end }}