{{- if .Values.service.extraService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.extraService.name }}
  labels:
    {{- include "uniconfig.labels" . | nindent 4 }}
  {{- with .Values.service.extraService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.extraService.type }}
  {{- if .Values.service.extraService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.extraService.loadBalancerIP | quote }}
  {{- end}}
  ports:
    - port: {{ .Values.service.extraService.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "uniconfig.selectorLabels" . | nindent 4 }}
{{- end }}
