{{- if .Values.ingress.enabled -}}
{{- $fullName := include "uniconfig.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "uniconfig.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if .Values.ingress.path }}
    - http:
        paths:
          - backend:
              service:
                name: {{ include "uniconfig.fullname" . }}
                port:
                  number: {{ $svcPort }}
            path: {{ .Values.ingress.path }}
            pathType: Prefix
    {{- end }}
{{- end }}
