{{- if (include "uniconfig.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uniconfig.fullname" . }}
data:
  POSTGRES_USERNAME: {{ .Values.dbPersistence.POSTGRES_USERNAME | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.dbPersistence.POSTGRES_PASSWORD | b64enc }}
  CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD: {{ .Values.dbPersistence.CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD | b64enc }}
{{- end -}}
