{{- if (include "uniconfig.createStorageSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azure.AKS.storage.accountName | b64enc }}
  azurestorageaccountkey: {{ .Values.azure.AKS.storage.accessKey | b64enc }}
{{ end }}
