{{- if (include "uniconfig.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uniconfig.fullname" . }}
data:
  DBPERSISTENCE_CONNECTION_USERNAME: {{ .Values.dbPersistence.DBPERSISTENCE_CONNECTION_USERNAME | b64enc }}
  DBPERSISTENCE_CONNECTION_PASSWORD: {{ .Values.dbPersistence.DBPERSISTENCE_CONNECTION_PASSWORD | b64enc }}
  DBPERSISTENCE_CONNECTION_SSLPASSWORD: {{ .Values.dbPersistence.DBPERSISTENCE_CONNECTION_SSLPASSWORD | b64enc }}
  CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD: {{ .Values.dbPersistence.CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD | b64enc }}
  TLS_KEYSTOREPASSWORD: {{ .Values.dbPersistence.TLS_KEYSTOREPASSWORD | b64enc }}
{{- end -}}
