{{- if (include "uniconfig.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uniconfig.fullname" . }}
data:
  dbPersistence_connection_username: {{ .Values.dbPersistence.connection_username | b64enc }}
  dbPersistence_connection_password: {{ .Values.dbPersistence.connection_password | b64enc }}
{{- end -}}
