apiVersion: v1
kind: Service
metadata:
  name: {{ include "uniconfig.fullname" . }}
  labels:
    {{- include "uniconfig.labels" . | nindent 4 }}
  annotations:
    "service.beta.kubernetes.io/azure-load-balancer-resource-group": "dns_shared"
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: "20.101.115.184"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "uniconfig.selectorLabels" . | nindent 4 }}
