{{- if .Values.traefik.ingress }}{{ if .Values.traefik.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniconfig
spec:
  defaultBackend:
    service:
      name: uniconfig
      port:
        number: 8181
  ingressClassName: nginx
  rules:
  - host: {{ .Values.traefik.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: uniconfig
            port:
              number: 8181
        path: /
        pathType: Prefix
{{- end }}{{ end }}