# Traefik service used as a load-ballancer to controller
{{- if .Values.highAvailability.enabled }}
{{- range $host := .Values.highAvailability.hosts }}
{{ $uc_host := ( include "uniconfig.fullname" $ ) }}
{{- if eq $host $uc_host }}
{{- fail (printf "You must use different traefik hostname: `%s` due to conflict with uniconfig service name : `%s`" $host $uc_host ) }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $host }}
spec:
  type: ClusterIP
  selector:
    {{- include "uniconfig.selectorLabelsForTraefik" $ | nindent 4 }}
  ports:
  - name: traefik-uniconfig-entrypoint 
    port: {{ $.Values.highAvailability.traefik.port }}
    targetPort: uniconfig
    protocol: TCP
---
{{- end }}
{{- end }}