apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-topology.fullname" . }}
  labels:
    {{- include "sample-topology.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $i, $e := until 300}}
    - name: {{add 17000 . | quote }}
      port: {{add 17000 . }}
      targetPort: {{add 17000 . }}
    {{- end }}
    {{- range $i, $e := until 16}}
    - name: {{add 10000 . | quote }}
      port: {{add 10000 . }}
      targetPort: {{add 10000 . }}
    {{- end }}
  selector:
    {{- include "sample-topology.selectorLabels" . | nindent 4 }}
