{{ if not .Values.volumes.azureFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-scripts
data:
  inventory_rbac.lua: {{ (.Files.Get "config/scripts/inventory_rbac.lua") | quote }}
  uniconfig_query_escape.lua: {{ (.Files.Get "config/scripts/uniconfig_query_escape.lua") | quote }}
  uniconfig_rbac.lua: {{ (.Files.Get "config/scripts/uniconfig_rbac.lua") | quote }}
  unistore_rbac.lua: {{ (.Files.Get "config/scripts/unistore_rbac.lua") | quote }}
  wp_azure_swagger.lua: {{ (.Files.Get "config/scripts/wp_azure_swagger.lua") | quote }}
  header_check.lua: {{ (.Files.Get "config/scripts/header_check.lua") | quote }}
{{ end }}
