{{ if not .Values.deployment.volumes.azureFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-partials
data:
  allowed_headers.tmpl: {{ (.Files.Get "config/partials/allowed_headers.tmpl") | quote }}
  jwt_config.tmpl: {{ (.Files.Get "config/partials/jwt_config.tmpl") | quote }}
  jwt_fake_config.tmpl: {{ (.Files.Get "config/partials/jwt_fake_config.tmpl") | quote }}
  modifiers.tmpl: {{ (.Files.Get "config/partials/modifiers.tmpl") | quote }}
{{ end }}
