apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-templates
data:
  frinx_frontend.tmpl: {{ (.Files.Get "config/templates/frinx_frontend.tmpl") | quote }}
  frinx_frontend_proxy.tmpl: {{ (.Files.Get "config/templates/frinx_frontend_proxy.tmpl") | quote }}
  inventory.tmpl: {{ (.Files.Get "config/templates/inventory.tmpl") | quote }}
  uniconfig.tmpl: {{ (.Files.Get "config/templates/uniconfig.tmpl") | quote }}
  resource.tmpl: {{ (.Files.Get "config/templates/resource.tmpl") | quote }}
  schellar.tmpl: {{ (.Files.Get "config/templates/schellar.tmpl") | quote }}
  unistore.tmpl: {{ (.Files.Get "config/templates/unistore.tmpl") | quote }}
  topology_discovery.tmpl: {{ (.Files.Get "config/templates/topology_discovery.tmpl") | quote }}
  performance_monitor.tmpl: {{ (.Files.Get "config/templates/performance_monitor.tmpl") | quote }}
  workflow_manager.tmpl: {{ (.Files.Get "config/templates/workflow_manager.tmpl") | quote }}
  swagger.tmpl: {{ (.Files.Get "config/templates/swagger.tmpl") | quote }}
