{{ if not .Values.volumes.azureFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-partials
data:
  allowed_headers.tmpl: {{ (.Files.Get "config/partials/allowed_headers.tmpl") | quote }}
  modifiers.tmpl: {{ (.Files.Get "config/partials/modifiers.tmpl") | quote }}
{{ end }}
