apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-partials
data:
  allowed_headers.tmpl: {{ (.Files.Get "config/partials/allowed_headers.tmpl") | quote }}
  content_header.tmpl: {{ (.Files.Get "config/partials/content_header.tmpl") | quote }}
  modifiers.tmpl: {{ (.Files.Get "config/partials/modifiers.tmpl") | quote }}
  uc_modifiers.tmpl: {{ (.Files.Get "config/partials/uc_modifiers.tmpl") | quote }}
