apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "krakend.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        {{ if .Values.azure.AKS.enabled }}
        - name: config
          azureFile:
            secretName: storage-secret
            shareName: frinxmachine-configs/krakend
            readOnly: false
        {{ else }}
        - name: config
          configMap:
            name: {{ template "krakend.fullname" . }}-krakenConfig
        - name: scripts
          configMap:
            name: {{ template "krakend.fullname" . }}-scripts
        {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "krakend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{ if .Values.azure.AKS.enabled }}
            - name: config
              mountPath: {{ .Values.mountPath }}
            {{ else }}
            - name: config
              mountPath: /etc/krakend/
            - name: scripts
              mountPath: /etc/krakend/scripts/
            {{ end }}
          env:
            {{ if .Values.azure.AKS.enabled }}
            - name: AZURE_KRAKEND_PLUGIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-auth
                  key: clientId
            - name: AZURE_KRAKEND_PLUGIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-auth
                  key: clientSecret
            - name: AZURE_KRAKEND_PLUGIN_JWT_VALUE_PREFIX
              value: "{{ .Values.azure.httpJwtPrefix }}"
            - name: KRAKEND_PORT
              value: "8080"
            - name: FC_ENABLE
              value: "1"
            - name: FC_SETTINGS
              value: "{{ .Values.mountPath }}settings"
            - name: FC_PARTIALS
              value: "{{ .Values.mountPath }}partials"
            - name: FC_TEMPLATES
              value: "{{ .Values.mountPath }}templates"
            {{ else }}
            - name: KRAKEND_PORT
              value: "8080"
            - name: FC_ENABLE
              value: "1"
            - name : JWT_PRODUCTION
              value: "false"
            {{ end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__health
              port: http
          readinessProbe:
            httpGet:
              path: /__health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
