apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-krakend: {{ include (print $.Template.BasePath "/configmap-krakend.yaml") . | sha256sum }}
        checksum/config-partials: {{ include (print $.Template.BasePath "/configmap-partials.yaml") . | sha256sum }}
        checksum/config-scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        checksum/config-settings: {{ include (print $.Template.BasePath "/configmap-settings.yaml") . | sha256sum }}
        checksum/config-templates: {{ include (print $.Template.BasePath "/configmap-templates.yaml") . | sha256sum }}
        checksum/config-templates: {{ include (print $.Template.BasePath "/configmap-nginx.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "krakend.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "krakend.fullname" . }}-krakend
        - name: partials
          configMap:
            name: {{ template "krakend.fullname" . }}-partials
        - name: scripts
          configMap:
            name: {{ template "krakend.fullname" . }}-scripts
        - name: settings
          configMap:
            name: {{ template "krakend.fullname" . }}-settings
        - name: templates
          configMap:
            name: {{ template "krakend.fullname" . }}-templates
        - name: nginx-conf
          configMap:
            name: {{ template "krakend.fullname" . }}-nginx-config
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "krakend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: "{{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag }}"
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/krakend/
            - name: partials
              mountPath: /etc/krakend/partials/
            - name: scripts
              mountPath: /etc/krakend/scripts/
            - name: settings
              mountPath: /etc/krakend/settings/
            - name: templates
              mountPath: /etc/krakend/templates/
          env:
            - name: FC_ENABLE
              value: "1"
            - name: FC_SETTINGS
              value: "/etc/krakend/settings"
            - name: FC_PARTIALS
              value: "/etc/krakend/partials" 
            - name: FC_TEMPLATES
              value: "/etc/krakend/templates"
            - name: KRAKEND_PORT
              value: "8000"
            - name: FC_OUT
              value: "/tmp/output.json"
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: TLS_DISABLED
              value: {{ .Values.env.TLS_DISABLED | quote }}
            - name: DEFAULT_TIMEOUT
              value: {{ .Values.env.DEFAULT_TIMEOUT | quote }}
            - name: KRAKEND_TLS_PROTOCOL
              value: {{ .Values.env.KRAKEND_TLS_PROTOCOL | quote }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.env.ALLOWED_HOSTS | quote }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.env.ALLOWED_ORIGINS | quote }}
            - name: UNICONFIG_PROTOCOL
              value: {{ .Values.env.UNICONFIG_PROTOCOL | quote }}
            - name: UNICONFIG_ZONES_LIST
              value: {{ .Values.env.UNICONFIG_ZONES_LIST | quote }}
            - name: UNICONFIG_TIMEOUT
              value: {{ .Values.env.UNICONFIG_TIMEOUT | quote }}
            - name: WORKFLOW_MANAGER_ENABLED
              value: {{ .Values.env.WORKFLOW_MANAGER_ENABLED | quote }}
            - name: UNICONFIG_ENABLED
              value: {{ .Values.env.UNICONFIG_ENABLED | quote }}
            - name: L3VPN_ENABLED
              value: {{ .Values.env.L3VPN_ENABLED | quote }}
            - name: INVENTORY_ENABLED
              value: {{ .Values.env.INVENTORY_ENABLED | quote }}
            - name: RESOURCE_MANAGER_ENABLED
              value: {{ .Values.env.RESOURCE_MANAGER_ENABLED | quote }}
            - name: DEVICE_TOPOLOGY_ENABLED
              value: {{ .Values.env.DEVICE_TOPOLOGY_ENABLED | quote }}
            # RBAC - UNICONFIG
            - name: UNICONFIG_CONTROLLER_ADMIN_GROUP
              value: {{ .Values.rbac.UNICONFIG_CONTROLLER_ADMIN_GROUP | quote }}
            # RBAC - UNISTORE
            - name: UNISTORE_CONTROLLER_ADMIN_GROUP
              value: {{ .Values.rbac.UNISTORE_CONTROLLER_ADMIN_GROUP | quote }}
            - name: UNISTORE_BEARER_ROLE
              value: {{ .Values.rbac.UNISTORE_BEARER_ROLE | quote }}
            - name: UNISTORE_SERVICE_ROLE
              value: {{ .Values.rbac.UNISTORE_SERVICE_ROLE | quote }}
            - name: UNISTORE_NETWORK_ROLE
              value: {{ .Values.rbac.UNISTORE_NETWORK_ROLE | quote }}
            - name: UNISTORE_OTHER_PERMITTED_ROLES
              value: {{ .Values.rbac.UNISTORE_OTHER_PERMITTED_ROLES | quote }}
            - name: UNISTORE_BEARER_NODE
              value: {{ .Values.rbac.UNISTORE_BEARER_NODE | quote }}
            - name: UNISTORE_SERVICE_NODE
              value: {{ .Values.rbac.UNISTORE_SERVICE_NODE | quote }}
            - name: UNISTORE_NETWORK_NODE
              value: {{ .Values.rbac.UNISTORE_NETWORK_NODE | quote }}
            # RBAC - INVENTORY
            - name: INVENTORY_ADMIN_GROUP
              value: {{ .Values.rbac.INVENTORY_ADMIN_GROUP | quote }}
            # RBAC - WORKFLOW_PROXY
            - name: ADMIN_ACCESS_ROLE
              value: {{ .Values.rbac.ADMIN_ACCESS_ROLE | quote }}
            # RBAC - WORKERS
            - name: X_AUTH_USER_GROUP
              value: {{ .Values.rbac.X_AUTH_USER_GROUP | quote }}
            # PROXY
            - name: PROXY_ENABLED
              value: {{ .Values.env.PROXY_ENABLED | quote }}
            # OAUTH2-PROXY
            - name: OAUTH2_KRAKEND_PLUGIN_TENANT_ID
              value: {{ .Values.env.OAUTH2_KRAKEND_PLUGIN_TENANT_ID | quote }}
            - name: OAUTH2_KRAKEND_PLUGIN_USER_ROLES_MAP
              value: {{ .Values.env.OAUTH2_KRAKEND_PLUGIN_USER_ROLES_MAP | quote }}
            - name: OAUTH2_KRAKEND_PLUGIN_USER_GROUPS_MAP
              value: {{ .Values.env.OAUTH2_KRAKEND_PLUGIN_USER_GROUPS_MAP | quote }}
            - name: OAUTH2_KRAKEND_PLUGIN_FROM_MAP
              value: {{ .Values.env.OAUTH2_KRAKEND_PLUGIN_FROM_MAP | quote }}              
            {{- if .Values.env.PROXY_ENABLED }}  
            - name: HTTP_PROXY
              value: {{ .Values.env.HTTP_PROXY | quote }}
            - name: HTTPS_PROXY
              value: {{ .Values.env.HTTPS_PROXY | quote }}
            - name: NO_PROXY
              value: "workflow-proxy,frinx-frontend,inventory,krakend,unistore,resource-manager,{{ .Values.env.NO_PROXY }},$(UNICONFIG_ZONES_LIST)"
            {{- end }}
          {{- range $key, $val := .Values.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: websocket
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__health
              port: http
            # httpGet:
            #   path: /health
            #   port: websocket
          readinessProbe:
            httpGet:
              path: /__health
              port: http
            # httpGet:
            #   path: /health
            #   port: websocket
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
