{{ if .Values.deployment.volumes.azureFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "krakend.fullname" . }}-azureStorage
type: Opaque
data:
  azurestorageaccountname: {{ .Values.deployment.volumes.azureFile.storage.accountName }}
  azurestorageaccountkey: {{ .Values.deployment.volumes.azureFile.storage.accessKey }}
{{ end }}
