{{- if .Values.deployment.azureAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "krakend.fullname" . }}-azure-auth
data:
  AZURE_KRAKEND_PLUGIN_CLIENT_ID: {{ .Values.deployment.azureAuth.AZURE_KRAKEND_PLUGIN_CLIENT_ID | b64enc }}
  AZURE_KRAKEND_PLUGIN_CLIENT_SECRET: {{ .Values.deployment.azureAuth.AZURE_KRAKEND_PLUGIN_CLIENT_SECRET | b64enc }}
{{- end }}
