apiVersion: v1
kind: Service
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.wsPort }}
      targetPort: websocket
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.wsNodePort }}
      {{- end }}
      protocol: TCP
      name: ws
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "krakend.selectorLabels" . | nindent 4 }}
