{{ if .Values.azure.aks.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azure.aks.storage.accountName }}
  azurestorageaccountkey: {{ .Values.azure.aks.storage.accessKey }}
{{ end }}