apiVersion: v2
name: frinx-grafana-configs
description: A Helm chart for Kubernetes deployment of the Frinx-grafana-configs
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: FRINX
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Pass additional datasources to frinx-grafana-datasources
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/42
