# Default values for frinx-grafana-configs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dashboards:
  files: "config/*"

datasources:
  influxdb2:
    name: InfluxDB
    url: http://influxdb
    basicAuth: true
    basicAuthUser: frinx
    defaultBucket: frinx
    httpMode: POST
    organization: frinx-machine
    basicAuthPassword: frinx123!
    token: eyJrIjoiN09MSVpVZjlVRG1xNHlLNXpVbmZJOXFLWU1GOXFxNEIiLCJuIjoic3Nzc3MiLCJpZCI6MX0
  loki:
    name: Loki
    url: http://loki:3100

extraDatasources: |
#   - name: Loki
#     type: loki
#     access: proxy
#     url: http://loki:3100
#     jsonData:
