# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.arango_operator_secret.initSecretName }}
type: "Opaque"
data:
  username: {{ default "" .Values.arango_operator_secret.username | b64enc | quote }}
  password: {{ default "" .Values.arango_operator_secret.password | b64enc | quote }}
