{{- if .Values.global.dbPersistence.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.global.dbPersistence.secretName }}
data:
  INVENTORY_POSTGRES_USERNAME: {{ .Values.global.dbPersistence.secrets.INVENTORY_POSTGRES_USERNAME | b64enc }}
  INVENTORY_POSTGRES_PASSWORD: {{ .Values.global.dbPersistence.secrets.INVENTORY_POSTGRES_PASSWORD | b64enc }}
  TD_ARANGO_USERNAME: {{ .Values.global.dbPersistence.secrets.TD_ARANGO_USERNAME | b64enc }}
  TD_ARANGO_ROOT_PASSWORD: {{ .Values.global.dbPersistence.secrets.TD_ARANGO_ROOT_PASSWORD | b64enc }}
  RM_POSTGRES_USERNAME: {{ .Values.global.dbPersistence.secrets.RM_POSTGRES_USERNAME | b64enc }}
  RM_POSTGRES_PASSWORD: {{ .Values.global.dbPersistence.secrets.RM_POSTGRES_PASSWORD | b64enc }}
  SCHELLAR_POSTGRES_USERNAME: {{ .Values.global.dbPersistence.secrets.SCHELLAR_POSTGRES_USERNAME | b64enc }}
  SCHELLAR_POSTGRES_PASSWORD: {{ .Values.global.dbPersistence.secrets.SCHELLAR_POSTGRES_PASSWORD | b64enc }}
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_USERNAME: {{ .Values.global.dbPersistence.secrets.CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_USERNAME | b64enc }}
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_PASSWORD: {{ .Values.global.dbPersistence.secrets.CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_PASSWORD | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.dbPersistence.secrets.SPRING_DATASOURCE_USERNAME | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.dbPersistence.secrets.SPRING_DATASOURCE_PASSWORD | b64enc }}
  SPRING_SEARCHDATASOURCE_USERNAME: {{ .Values.global.dbPersistence.secrets.SPRING_SEARCHDATASOURCE_USERNAME | b64enc }}
  SPRING_SEARCHDATASOURCE_PASSWORD: {{ .Values.global.dbPersistence.secrets.SPRING_SEARCHDATASOURCE_PASSWORD | b64enc }}
  UNICONFIG_POSTGRES_USERNAME: {{ .Values.global.dbPersistence.secrets.UNICONFIG_POSTGRES_USERNAME | b64enc }}
  UNICONFIG_POSTGRES_PASSWORD: {{ .Values.global.dbPersistence.secrets.UNICONFIG_POSTGRES_PASSWORD | b64enc }}
  UNICONFIG_CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD: {{ .Values.global.dbPersistence.secrets.UNICONFIG_CLISHELL_SSHSERVER_USERNAMEPASSWORDAUTH_PASSWORD | b64enc }}
{{- end -}}
