{{- if .Values.externalsecret }}{{ if .Values.externalsecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalsecret.secretstorename }}
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
    name: regcred
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: common/regcred
      property: .dockerconfigjson
{{- end }}{{ end }}
