apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBGgk73uIX4Fg4sWAjNPmavWf7IYtzGYbkwLRckjCjKJOrmfSSukPj26Sgymj0dQoUahyEVhp/vg3N4fszBUZ8hasSUm5Uk5F3ZdVbeDUcjk3s8lfnCPzklQ9TWzZ+sB+rWRvVzyxRpkVz13NLdtF9UhXDl3pz3Fqj9Pml4YYaVMr5IDjz/NLZ4SIGtVycHVPOk84qNjEKlMHebrXbwOGA/3b7dG8OiriiCj2cJaevHa8dB+1RgCiWei3hry5X9YpHymf5lBuIDXXWGjqbR2yp618D0Ray+DKhwA5KQGAsG6JLTZMfOGZzfIIt+uIG/EhvrMvfNIR64Tjc12RErIErKFQaFCLxOuXLjh2L5gU7hI46X7cQ9vpJMwgOFPJ6Y6JLBHvKBcdl/vwwUrRa2bJBcI/pTWN9lwr5SlmZK+12HNJLdKZpupcZVoZc83nEsryULudgHmNuVUrYinfta4YIZJC7lWoD8h8q81B4tYTrmRRUOEy3DV73p5kuX78LAOz534Tdd5AY8ca0lgn/Dd93IBYiu3kliILSxS9K2PmU3si4Sd9X3dCl5m9smTSBta1IloIDUHgOfCMz+UFHf5syQscAUTX/DgYTOHnqWiy8jlI3YAL5E9cI6tI1dClfZhMElnKce5TPevWUmzLBA/lYedNpx+4eapNtYZPEmhCAJrZZaPYDWb16yWhvTj5mSxSqcwIHZr7uElz0erLUfkiNPquJZRzCPlDyilHBg/AiIuhj9+037Te/7b9B0OWtAnpjkmBDqpo/LaPPQr11tmJBAFyli1Y6LIb7iBRNIWkVIXFwRGh4vflJbBMwJL1cm+Gn0q9ggcmzR1g79LvdIg7NANEKtHfwvbsZu+Bt1z+quA2UBnvY1qgTvKpt5F9BL5o595UzqMlw7YfOT/C+3C90f/CfP5kJy576YpiZh5DqA5buKJLwiLH+VBXb0C1eONAFPpLE3jqlwecWK3Ina
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson

