apiVersion: batch/v1
kind: Job
metadata:
  name: device-discovery-seed-{{ .Release.Revision }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # "helm.sh/hook": post-install, post-upgrade
    # "helm.sh/hook-weight": "-5"
    # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  # parallelism: 2
  ttlSecondsAfterFinished: 10
  template:
    spec:
      initContainers:
      # ArangoDB database feeding
      - name: arango-seed
        image: {{ .Values.frinx_machine.arango_seed.image }}
        env:
        {{- range $key, $val := .Values.frinx_machine.arango_seed.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
        {{- end }}
        command: ["/app/arango_seed.sh", "app"]
        volumeMounts:
        - name: {{ .Values.frinx_machine.arango_seed.configName | quote }}
          mountPath: /app
      # Inventory database feeding, import devices and blueprint
      - name: inventory-seed
        image: {{ .Values.frinx_machine.inventory_seed.image }}
        env:
        {{- range $key, $val := .Values.frinx_machine.inventory_seed.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
        {{- end }}
        command:
          - /bin/bash
          - -c 
          - "pip3 install python_graphql_client==0.4.3 && python3 /app/importDevices.py /app/device_values.csv /app/device_blueprint.txt"
        volumeMounts:
        - name: {{ .Values.frinx_machine.arango_seed.configName | quote }}
          mountPath: /app
      # Load configmap with arangodb and inventory datas/scripts
      containers:
        - name: job-done
          image: busybox
          command: ['sh', '-c', 'echo "Check job container logs to see import results"']
      restartPolicy: Never
      volumes:
        - name: {{ .Values.frinx_machine.arango_seed.configName | quote }}
          configMap:
            name: {{ .Values.frinx_machine.arango_seed.configName | quote }}
            defaultMode: 0777

  backoffLimit: 10
  # podFailurePolicy:
  #   rules:
  #   - action: FailJob
  #     onExitCodes:
  #       containerName: arango-seed      # optional
  #       operator: In             # one of: In, NotIn
  #       values: [1]
    # - action: FailJob
    #   onExitCodes:
    #     containerName: inventory-seed      # optional
    #     operator: In             # one of: In, NotIn
    #     values: [1]
