apiVersion: v2
name: frinx-machine-operators
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
description: A Helm chart for installing operators and crds.
version: 0.2.0
appVersion: 6.1.0
maintainers:
  - name: FRINX
    email: services@frinx.io
    url: https://frinx.io
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.21.5
    condition: cloudnative-pg.enabled
  - name: kube-arangodb
    version: 1.2.41
    repository: https://arangodb.github.io/kube-arangodb
    condition: kube-arangodb.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Upgrade dependency version for Frinx Machine 6.1
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/392
