apiVersion: v2
name: frinx-machine-operators
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
description: A Helm chart for installing operators and crds.
version: 0.3.0
appVersion: 6.1.0
maintainers:
  - name: FRINX
    email: services@frinx.io
    url: https://frinx.io
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.21.5
    condition: cloudnative-pg.enabled
  - name: kube-arangodb
    version: 1.2.41
    repository: https://arangodb.github.io/kube-arangodb
    condition: kube-arangodb.enabled
  - name: prometheus-operator-crds
    version: 13.0.1
    repository: https://prometheus-community.github.io/helm-charts/
    condition: prometheus-operator-crds.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added dependency for prometheus crds
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/415
