apiVersion: v2
name: swagger-ui
description: A Helm chart for Swagger UI
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 0.2.0
appVersion: "v5.17.14"
engine: gotpl
maintainers:
  - name: FRINX
    email: services@frinx.io
    url: https://frinx.io
annotations:
  artifacthub.io/images: |
    - name: swagger-ui
      image: swaggerapi/swagger-ui
  artifacthub.io/changes: |
    - kind: added
      description: Fixed endpoint for obtaining executed workflows from workflow-manager
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/405
