apiVersion: v1
kind: Service
metadata:
  name: {{ include "tftp.fullname" . }}
  labels:
    {{- include "tftp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: UDP
      nodePort: 31000
      name: {{ .Values.service.port | quote }}
    {{- range $i, $e := until 15}}
    - name: {{add 31001 . | quote }}
      port: {{add 31001 . }}
      nodePort: {{add 31001 . }}
      targetPort: {{add 31001 . }}
      protocol: UDP
    {{- end }}
  selector:
    {{- include "tftp.selectorLabels" . | nindent 4 }}
