apiVersion: v2
name: uniresource
description: A Helm chart for Kubernetes deploying of the Frinx Uniresource
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.1.0
appVersion: "1.0.4"
maintainers:
  - name: FRINX
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Add security context to container
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/43
    - kind: added
      description: Add WASMER_MAX_TIMEOUT_MILLIS env variable
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/43
    - kind: changed
      description: Update uniresource version to 1.0.4
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/43
