apiVersion: v2
name: frinx-machine
description: Kubernetes deployment of FRINX-machine
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 0.4.88
maintainers:
  - name: FRINX
dependencies:
  - condition: krakend.enabled
    name: krakend
    repository: file://../krakend
    # repository: https://FRINXio.github.io/helm-charts
    version: 2.10.0

  - condition: frinx-frontend.enabled
    name: frinx-frontend
    repository: file://../frinx-frontend
    # repository: https://FRINXio.github.io/helm-charts
    version: 3.1.2

  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13

  - condition: resource-manager.enabled
    name: resource-manager
    repository: file://../resource-manager
    version: 1.1.1

  - condition: workflow-manager.enabled
    name: workflow-manager
    repository: file://../workflow-manager
    # repository: https://FRINXio.github.io/helm-charts
    version: 2.1.0

  - condition: inventory.enabled
    name: inventory
    repository: file://../inventory
    # repository: https://FRINXio.github.io/helm-charts
    version: 4.1.0

  - condition: uniconfig-postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
    alias: uniconfig-postgresql

  - condition: uniconfig.enabled
    name: uniconfig
    repository: file://../uniconfig
    version: 5.0.1

  - condition: demo-workflows.enabled
    name: demo-workflows
    repository: file://../demo-workflows
    # repository: https://FRINXio.github.io/helm-charts
    version: 1.3.0

  - condition: sample-topology.enabled
    name: sample-topology
    repository: https://FRINXio.github.io/helm-charts
    version: 2.0.0

  - condition: frinx-arango-config.enabled
    name: kube-arangodb
    version: 1.2.26
    repository: https://arangodb.github.io/kube-arangodb

  - condition: frinx-arango-config.enabled
    name: frinx-arango-config
    repository: file://../frinx-arango-config
    # repository: https://FRINXio.github.io/helm-charts
    version: 3.0.0

  - condition: topology-discovery.enabled
    name: topology-discovery
    version: 2.4.0
    repository: file://../topology-discovery
    # repository: https://FRINXio.github.io/helm-charts

  - condition: grafana.enabled
    name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: 6.52.9

  - condition: grafana.enabled
    name: frinx-grafana-configs
    repository: "https://FRINXio.github.io/helm-charts"
    version: 1.x.x

  # - condition: influxdb.enabled
  #   name: influxdb2
  #   repository: "https://helm.influxdata.com"
  #   version: 2.1.0

  # - condition: telegraf-ds.enabled
  #   name: telegraf-ds
  #   repository: https://helm.influxdata.com
  #   version: 1.1.1

  # - condition: loki.enabled
  #   name: loki
  #   repository: https://grafana.github.io/helm-charts
  #   version: 2.16.0

  # - condition: loki.enabled
  #   name: promtail
  #   repository: https://grafana.github.io/helm-charts
  #   version: 6.3.0

  - condition: cloudnative-pg.enabled
    name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.19.0

  - condition: workflow-manager-postgres.enabled
    name: cloud-native-pg
    alias: workflow-manager-postgres
    version: 0.0.1
    repository: https://FRINXio.github.io/helm-charts

  - condition: uniconfig-postgres.enabled
    name: cloud-native-pg
    alias: uniconfig-postgres
    version: 0.0.1
    repository: https://FRINXio.github.io/helm-charts

  # - condition: pgadmin4.enabled
  #   name: pgadmin4
  #   repository: "https://helm.runix.net"
  #   version: 1.18.2

  - condition: oauth2-proxy.enabled
    name: oauth2-proxy
    repository: https://oauth2-proxy.github.io/manifests
    version: 6.17.0

  - condition: oauth2-proxy.enabled
    name: oauth2-proxy-assets
    repository: file://../oauth2-proxy-assets
    # repository: https://oauth2-proxy.github.io/manifests
    version: 0.0.1

  # - name: dex
  #   repository: https://charts.dexidp.io
  #   version: 0.16.0

  # - name: whoami
  #   repository: https://cowboysysop.github.io/charts/
  #   version: 5.1.0
