krakend:
  service:
    type: LoadBalancer

postgresql:
  global:
    storageClass: longhorn

uniconfig-postgresql:
  global:
    storageClass: longhorn

demo-workflows:
  enabled: true

sample-topology:
  enabled: true

influxdb2:
  persistence:
    storageClass: longhorn

telegraf-ds:
  rbac:
    create: false

grafana:
  service:
    type: LoadBalancer
