# Global settings

x-frinx-image-pull-secret: &frinx-image-pull-secret regcred
x-device-discovery-enabled: &device-discovery-enabled true

# tags:
#   crds: false
#   statefulpg: false
#   monitoring: false
#   frinx-machine: false
#   base: false
#   frinx-machine-db: false
#   workflow-manager-postgres: false
#   uniconfig-postgres: false
#   frinx-arango-config: false

# CRDs
kube-arangodb:
  enabled: true
  operator:
    replicaCount: 2
    args:
      - --deployment.feature.ephemeral-volumes=true
  rbac:
    enabled: false
    extensions:
      monitoring: false
      acs: false
      at: false

cloudnative-pg:
  enabled: true

# Stateful PG
postgresql:
  enabled: false
  fullnameOverride: "frinx-postgresql"
  auth:
    enablePostgresUser: true
    username: postgresU
    password: postgresP
    database: postgres
  architecture: standalone
  primary:
    initdb:
      scripts:
        init_db.sql: |
          CREATE DATABASE schellar;
          CREATE DATABASE conductor;
          CREATE DATABASE inventory;

uniconfig-postgresql:
  enabled: false
  fullnameOverride: "uniconfig-postgresql"
  auth:
    enablePostgresUser: true
    username: postgresU
    password: postgresP
    database: uniconfig
  architecture: standalone

# Monitoring

grafana:
  enabled: false
  fullnameOverride: "grafana"
  adminUser: frinx
  adminPassword: frinx123!

  extraConfigmapMounts:
    - name: frinx-grafana-datasources
      mountPath: /etc/grafana/provisioning/datasources
      subPath: ""
      configMap: frinx-grafana-datasources
      readOnly: false
    - name: frinx-grafana-dashboards
      mountPath: /etc/grafana/provisioning/dashboards
      subPath: ""
      configMap: frinx-grafana-dashboards
      readOnly: false

influxdb2:
  enabled: false
  fullnameOverride: influxdb
  adminUser:
    user: "frinx"
    password: "frinx123!"
    token: "eyJrIjoiN09MSVpVZjlVRG1xNHlLNXpVbmZJOXFLWU1GOXFxNEIiLCJuIjoic3Nzc3MiLCJpZCI6MX0"
    organization: "frinx-machine"
    bucket: "frinx"
    retention_policy: "2d"
  # env:
  #   - name: DOCKER_INFLUXDB_INIT_MODE
  #     value: setup

telegraf-ds:
  enabled: false
  fullnameOverride: telegraf-ds
  env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  config:
    docker_endpoint: ""

  override_config:
    toml: |
      [agent]
        collection_jitter = "0s"
        debug = false
        flush_interval = "10s"
        flush_jitter = "0s"
        hostname = "$HOSTNAME"
        interval = "10s"
        logfile = ""
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        omit_hostname = false
        precision = ""
        quiet = false
        round_interval = true

      [[outputs.influxdb_v2]]
        bucket = "frinx"
        organization = "frinx-machine"
        token = "eyJrIjoiN09MSVpVZjlVRG1xNHlLNXpVbmZJOXFLWU1GOXFxNEIiLCJuIjoic3Nzc3MiLCJpZCI6MX0"
        urls = ["http://influxdb"]

      [[outputs.health]]
        service_address = "http://:8080"

      [[inputs.diskio]]
      [[inputs.kernel]]
      [[inputs.mem]]
      [[inputs.net]]
      [[inputs.processes]]
      [[inputs.swap]]
      [[inputs.system]]

      [[inputs.cpu]]
        percpu = true
        totalcpu = true
        collect_cpu_time = false
        report_active = false

      [[inputs.disk]]
        ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

      [[inputs.kubernetes]]
        url = "https://$HOSTIP:10250"
        bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify = true
        [inputs.kubernetes.tagpass]
          namespace = [ "${NAMESPACE}" ]

loki:
  enabled: false
  fullnameOverride: loki
  loki: 
    config: |
      chunk_store_config:
        max_look_back_period: 24h
      table_manager:
        retention_deletes_enabled: false
        retention_period: 24h

promtail:
  fullnameOverride: promtail
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
      scrapeConfigs: |
        - job_name: kubernetes-pods
          pipeline_stages:
            {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - {{ .Release.Namespace }}
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_controller_name
              regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
              action: replace
              target_label: __tmp_controller_name
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
                - __tmp_controller_name
                - __meta_kubernetes_pod_name
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: app
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                - __meta_kubernetes_pod_label_release
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: instance
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
                - __meta_kubernetes_pod_label_component
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: component
            {{- if .Values.config.snippets.addScrapeJobLabel }}
            - replacement: kubernetes-pods
              target_label: scrape_job
            {{- end }}
            {{- toYaml .Values.config.snippets.common | nindent 4 }}
            {{- with .Values.config.snippets.extraRelabelConfigs }}
            {{- toYaml . | nindent 4 }}
            {{- end }}

### Default values for FRINX-machine.

# Database configuration

uniconfig-postgres:
  enabled: true
  name: uniconfig-postgresql
  imageName: "ghcr.io/cloudnative-pg/postgresql:12.18"

  bootstrap:
    initdb:
      database: uniconfig
      owner: postgresU

  secrets:
    superuserSecret:
      username: postgres
      password: postgres
    userSecret:
      username: postgresU
      password: postgresP


workflow-manager-postgres:
  enabled: true
  name: postgresql
  imageName: "ghcr.io/cloudnative-pg/postgresql:12.18"

  bootstrap:
    initdb:
      postInitApplicationSQLRefs:
        secretRefs:
          - name: postgresql-post-init-sql-secret
            key: secret.sql

  secrets:
    superuserSecret:
      username: postgres
      password: postgres
    userSecret:
      username: frinx
      password: postgres
    postInitSqlSecret:
      sql: |-
        CREATE ROLE schellar LOGIN PASSWORD 'schellar';
        GRANT CONNECT ON DATABASE frinx TO schellar;
        CREATE USER schellar_user WITH PASSWORD 'schellar';
        GRANT schellar TO schellar_user;
        CREATE SCHEMA schellar AUTHORIZATION schellar;
        ALTER ROLE schellar SET search_path=schellar;
        ALTER USER schellar_user SET search_path TO schellar;
        CREATE ROLE inventory LOGIN PASSWORD 'inventory';
        GRANT CONNECT ON DATABASE frinx TO inventory;
        CREATE USER inventory_user WITH PASSWORD 'inventory';
        GRANT inventory TO inventory_user;
        CREATE SCHEMA inventory AUTHORIZATION inventory;
        ALTER ROLE inventory SET search_path=inventory;
        ALTER USER inventory_user SET search_path TO inventory;
        CREATE ROLE conductor LOGIN PASSWORD 'conductor';
        GRANT CONNECT ON DATABASE frinx TO conductor;
        CREATE USER conductor_user WITH PASSWORD 'conductor';
        GRANT conductor TO conductor_user;
        CREATE SCHEMA conductor AUTHORIZATION conductor;
        CREATE SCHEMA archive AUTHORIZATION conductor;
        CREATE SCHEMA external AUTHORIZATION conductor;
        ALTER ROLE conductor SET search_path=public,conductor,archive,external;
        ALTER USER conductor_user SET search_path TO conductor,archive,external;
        CREATE ROLE resource LOGIN PASSWORD 'resource';
        GRANT CONNECT ON DATABASE frinx TO resource;
        CREATE USER resource_user WITH PASSWORD 'resource';
        GRANT resource TO resource_user;
        CREATE SCHEMA resource AUTHORIZATION resource;
        ALTER ROLE resource SET search_path=resource;
        ALTER USER resource_user SET search_path TO resource;

frinx-arango-config:
  enabled: true
  arangodb_config:
    enabled: *device-discovery-enabled
    image:
      repository: arangodb/arangodb
      tag: 3.9.9-noavx
    # securityContext:
    #   readOnlyRootFilesystem: true
    #   runAsUser: 1000
    #   runAsGroup: 2000
    #   fsGroup: 3000
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: app
    #           operator: In
    #           values:
    #           - arangobd

# Component configuration

krakend:
  enabled: true
  fullnameOverride: "krakend"

  image:
    repository: "frinx/krakend"
    tag: "6.0.0-rc-1"

  rbac:
    UNICONFIG_CONTROLLER_ADMIN_GROUP: "FRINXio"
    UNISTORE_CONTROLLER_ADMIN_GROUP: "FRINXio"
    UNISTORE_BEARER_ROLE: ""
    UNISTORE_SERVICE_ROLE: ""
    UNISTORE_NETWORK_ROLE: ""
    UNISTORE_OTHER_PERMITTED_ROLES: ""
    UNISTORE_BEARER_NODE: "bearer"
    UNISTORE_SERVICE_NODE: "service"
    UNISTORE_NETWORK_NODE: "network"
    INVENTORY_ADMIN_GROUP: "FRINXio"
    ADMIN_ACCESS_ROLE: "FRINXio"
    X_AUTH_USER_GROUP: "FRINXio"

  env:
    L3VPN_ENABLED: true
    DEVICE_TOPOLOGY_ENABLED: true

frinx-frontend:
  enabled: true
  fullnameOverride: "frinx-frontend"

  image:
    repository: "frinx/frinx-frontend"
    tag: "latest"
    pullPolicy: "Always"

  proxyImage:
    name: frinx/frinx-graphql-proxy
    tag: "latest"
    pullPolicy: "Always"

  env:
    AUTH_CLIENT_ID: "frinx"
    DEVICE_TOPOLOGY_ENABLED: true
    INVENTORY_API_URL: "/api/proxy"
    RESOURCE_MANAGER_API_URL: "/api/proxy"
    AUTH_ENABLED: true

  proxyEnv:
    DEBUG: 1

oauth2-proxy:
  enabled: true
  fullnameOverride: "oauth2-proxy"

  image:
    repository: "simonmisencik/oauth2-proxy"
    tag: "v47c0de2-dirty"
    pullPolicy: "Always"

  config:
    cookieSecret: 
    clientSecret: 
    clientID: 
    configFile: |-
      github_org = "FRINXio"  # Replace with your GitHub org name, or github_team=team_name to limit access to a specific team
      scope = "user:email read:org groups"
      email_domains = [ "*" ]  # Replace with [ "example.com" ] to limit access to users with specific email domain
      provider = "github"
      cookie_secure = true
      cookie_domains = [ "chart-example.local" ]  # Replace with domain names that the proxy is allowed to redirect to after auth
      whitelist_domains = [ "chart-example.local" ]  # Same as above

  extraArgs:
    - --provider=github
    - --upstream=http://krakend:8080
    - --redirect-url=http://chart-example.local/oauth2/callback
    - --cookie-secure=false
    - --pass-authorization-header
    - --login-url=https://github.com/login/oauth/authorize
    - --custom-sign-in-logo=/data/custom-logo/logo-min.png
    # - --custom-templates-dir=/data/custom-templates

  extraVolumes:
    - name: custom-logo
      configMap:
        name: frinx-oauth2-proxy-logo

  extraVolumeMounts:
    - name: custom-logo
      mountPath: "/data/custom-logo"
      readOnly: true

resource-manager:
  enabled: true
  fullnameOverride: "resource-manager"

  image:
    repository: "frinx/resource-manager"
    tag: "6.0.0_rc1"
    pullPolicy: "Always"

  postgresql:
    enabled: false

  dbPersistence:
    POSTGRES_HOST: postgresql-rw
    POSTGRES_DATABASE: frinx
    POSTGRES_USERNAME: resource_user
    POSTGRES_PASSWORD: resource

  rbac:
    RM_ADMIN_ROLES: FRINXio
    RM_ADMIN_GROUPS: FRINXio

workflow-manager:
  enabled: true
  fullnameOverride: "conductor-server"

  image:
    repository: "frinx/conductor-server"
    tag: "latest"

  schellarImage:
    repository: "frinx/schellar"
    tag: "4.0.0"

  postgresql:
    enabled: false

  conductorExtraEnv:
    SPRING_SEARCHDATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 8

  dbPersistence:
    SPRING_DATASOURCE_HOST: postgresql-rw
    SPRING_SEARCHDATASOURCE_HOST: postgresql-rw
    CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_HOST: postgresql-rw
    POSTGRES_DATABASE: frinx
    CONDUCTOR_DATASOURCE_SCHEMA: conductor
    POSTGRES_DB_SCHEMA: conductor
    existingSecret:
    CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_USERNAME: conductor_user
    CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_PASSWORD: conductor
    SPRING_DATASOURCE_USERNAME: conductor_user
    SPRING_DATASOURCE_PASSWORD: conductor
    SPRING_SEARCHDATASOURCE_USERNAME: conductor_user
    SPRING_SEARCHDATASOURCE_PASSWORD: conductor

  schellarDbPersistence:
    POSTGRES_HOST: postgresql-rw
    POSTGRES_DATABASE: frinx
    POSTGRES_USERNAME: schellar_user
    POSTGRES_PASSWORD: schellar

inventory:
  enabled: true
  fullnameOverride: "inventory"

  image:
    repository: "frinx/frinx-inventory-server"
    tag: "latest"
    pullPolicy: "Always"

  postgresql:
    enabled: false

  dbPersistence:
    POSTGRES_HOST: "postgresql-rw"
    POSTGRES_DATABASE: frinx
    POSTGRES_DB_SCHEMA: inventory
    POSTGRES_USERNAME: inventory
    POSTGRES_PASSWORD: inventory
  env:
    TOPOLOGY_ENABLED: *device-discovery-enabled

topology-discovery:
  enabled: *device-discovery-enabled
  fullnameOverride: "topology-discovery"

  image:
    repository: "frinx/topology-discovery"
    tag: "6.0.0"

  imagePullSecrets:
    - name: *frinx-image-pull-secret

  dbPersistence:
    ARANGO_URL: 'http://arangodb:8529'
    ARANGO_USERNAME: 'root'
    ARANGO_ROOT_PASSWORD: 'frinx'

uniconfig:
  enabled: true
  fullnameOverride: "uniconfig"

  image:
    repository: "frinx/uniconfig"
    tag: "6.0.0"

  imagePullSecrets:
    - name: *frinx-image-pull-secret

  postgresql:
    enabled: false
    
  dbPersistence:
    POSTGRES_HOST: "uniconfig-postgresql-rw"
    POSTGRES_USERNAME: postgresU
    POSTGRES_PASSWORD: postgresP

  traefik:
    enabled: true


  securityContext:
    capabilities:
      add:
      - NET_BIND_SERVICE
      drop:
      - ALL

  traefikExtraService:
    enabled: true
    name: "unistore"


traefik:
  fullnameOverride: "uniconfig"
  enabled: false

  ingress:
    enabled: true
    host: uniconfig.10.19.0.39.nip.io
  rbac:
    namespaced: true

  ingressClass:
    enabled: false
  ingressRoute:
    dashboard:
      enabled: false
  service:
    type: ClusterIP
  ports:
    uniconfig:
      port: 8181
      expose: true
      exposedPort: 8181
      protocol: TCP
  providers:
    kubernetesIngress:
      ingressClass: traefik-uniconfig
      # labelSelector: environment=development


# swaggerui: 
#   swaggerui.jsonUrl: http://uniconfig:8181/rests/openapi/uniconfig