apiVersion: v2
name: uniresource
description: A Helm chart for Kubernetes deploying of the Frinx Uniresource
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.0.1
appVersion: "1.0.3"
maintainers:
  - name: FRINX
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix DB hostname in initContainer if it is different from the default
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/16
    - kind: changed
      description: Increase probes time
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/16
