# Default values for conductor and proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas of the deployment
replicaCount: 1

image:
  # -- Resource-manager image repository
  repository: frinx/conductor-server
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

schellarImage:
  # -- Schellar image repository
  repository: frinx/schellar
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag
  tag: "6.1.0"

# -- [Image Pull Secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
imagePullSecrets: []
# -- String to partially override app name
nameOverride: ""
# -- String to fully override app name
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: conductor

# -- Pod annotations
podAnnotations: {}

# -- Configure [Pods Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
podSecurityContext: {}
  # fsGroup: 2000

# -- Configure [Container Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
securityContext:
  capabilities:
    drop:
    - ALL

service:
  # -- Service type
  type: ClusterIP
  # -- Schellar service port
  portSchellar: 3000
  # -- Conductor service port
  portConductor: 8080

# Configure the [Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/)
ingress:
  # -- Enable ingress
  enabled: false
  # -- IngressClass that will be be used to implement the Ingress
  className: ""
  # -- Additional labels for the Ingress resource
  labels: {}
  # -- Additional annotations for the Ingress resource
  annotations: {}
  # -- [Ingress Host](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource)
  hosts:
    - host: workflow-manager.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  schellarHosts:
    - host: workflow-manager-schellar.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- [Ingress TLS resource](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls)
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- [Container resources](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/)
resources: {}

# -- [Autoscaling parameters](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- [Node labels for pod assignment](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
nodeSelector: {}

# -- [Tolerations for pod assignment](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)
tolerations: []

# -- [Affinity for pod assignment](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)
affinity: {}

dbPersistence:
  # -- Datasource host
  SPRING_DATASOURCE_HOST:
  SPRING_SEARCHDATASOURCE_HOST:
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_HOST:
  POSTGRES_DATABASE: conductor
  CONDUCTOR_DATASOURCE_SCHEMA: public
  existingSecret:
    secretName:
    conductorExternalpayloadstoragePostgresUsernameKey:
    conductorExternalpayloadstoragePostgresPasswordKey:
    springDatasourceUsernameKey:
    springDatasourcePasswordKey:
    springSearchdatasourceUsernameKey:
    springSearchdatasourcePasswordKey:
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_USERNAME: postgresU
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_PASSWORD: postgresP
  SPRING_DATASOURCE_USERNAME: postgresU
  SPRING_DATASOURCE_PASSWORD: postgresP
  SPRING_SEARCHDATASOURCE_USERNAME: postgresU
  SPRING_SEARCHDATASOURCE_PASSWORD: postgresP

# -- Conductor extra ENV
conductorEnv:
  CONFIG_PROP: /app/nofile/config.properties
  _JAVA_OPTIONS: -Xmx2g
  LOG4J_PROP: /app/config/log4j-cluster.properties

# -- RBAC configuration
rbac:
  WM_ADMIN_ROLES: OWNER
  WM_ADMIN_GROUPS: NETWORK-ADMIN

# -- Conductor extra ENV
conductorExtraEnv:
  CONDUCTOR_APP_OWNEREMAILMANDATORY: false
  CONDUCTOR_DB_TYPE: postgres
  SPRING_SEARCHDATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 8
  CONDUCTOR_APP_ASYNCINDEXINGENABLED: false
  CONDUCTOR_INDEXING_ENABLED: false
  CONDUCTOR_ARCHIVE_DB_TYPE: postgres
  CONDUCTOR_ARCHIVE_DB_ENABLED: true
  CONDUCTOR_ARCHIVE_DB_INDEXER_THREADCOUNT: 4
  CONDUCTOR_ARCHIVE_DB_INDEXER_POLLINGINTERVAL: 10
  CONDUCTOR_ADDITIONAL_MODULES: com.netflix.conductor.contribs.metrics.MetricsRegistryModule,com.netflix.conductor.contribs.metrics.LoggingMetricsModule
  CONDUCTOR_METRICSLOGGER_ENABLED: true
  CONDUCTOR_METRICSLOGGER_REPORTPERIODSECONDS: 15
  CONDUCTOR_METRICSDATADOG_ENABLED: false
  # Increase payload threshold limits for transferring big schemas to PostgreSQL
  CONDUCTOR_APP_WORKFLOWINPUTPAYLOADSIZETHRESHOLD: 85
  CONDUCTOR_APP_WORKFLOWOUTPUTPAYLOADSIZETHRESHOLD: 85
  CONDUCTOR_APP_MAXWORKFLOWINPUTPAYLOADSIZETHRESHOLD: 102400
  CONDUCTOR_APP_MAXWORKFLOWOUTPUTPAYLOADSIZETHRESHOLD: 102400
  CONDUCTOR_APP_TASKINPUTPAYLOADSIZETHRESHOLD: 85
  CONDUCTOR_APP_TASKOUTPUTPAYLOADSIZETHRESHOLD: 85
  CONDUCTOR_APP_MAXTASKINPUTPAYLOADSIZETHRESHOLD: 102400
  CONDUCTOR_APP_MAXTASKOUTPUTPAYLOADSIZETHRESHOLD: 102400
  # PostgreSQL External Payload Storage variables
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_TYPE: postgres
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_CONDUCTORURL: http://conductor-server:8080
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_MAXDATAROWS: 100000
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_MAXDATADAYS: 0
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_MAXDATAMONTHS: 0
  CONDUCTOR_EXTERNALPAYLOADSTORAGE_POSTGRES_MAXDATAYEARS: 1
  LOADSAMPLE: false
  # Internal conductor properties
  CONDUCTOR_APP_EXECUTORSERVICEMAXTHREADCOUNT: 100
  CONDUCTOR_APP_SYSTEMTASKWORKERCALLBACKDURATION: 10
  CONDUCTOR_APP_WORKFLOWOFFSETTIMEOUT: 5
  CONDUCTOR_APP_TASKEXECUTIONPOSTPONEDURATION: 0
  CONDUCTOR_APP_WORKFLOWEXECUTIONLOCKENABLED: true
  # Frinx contribution configs
  CONDUCTOR_WORKFLOWEXECUTIONLOCK_TYPE: local_only
  CONDUCTOR_WORKFLOWREPAIRSERVICE_ENABLED: false
  SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  # Monitoring
  CONDUCTOR_METRICSPROMETHEUS_ENABLED: true
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus



# -- Schellar resources
schellarResources: {}

# -- Schellar DB chart configuration
schellarDbPersistence:
  POSTGRES_HOST: postgresql
  POSTGRES_PORT: 5432
  POSTGRES_DATABASE: schellar
  existingSecret:
    secretName:
    postgresUsernameKey:
    postgresPasswordKey:
  POSTGRES_USERNAME: postgresU
  POSTGRES_PASSWORD: postgresP

schellarEnv:
  # -- Shellar log level
  LOG_LEVEL: debug
  CHECK_INTERVAL_SECONDS: 10
  CONDUCTOR_API_URL: http://localhost:8080/api
  BACKEND: postgres
  POSTGRES_MIGRATIONS_DIR: migrations
  PLAYGROUND_QUERY_ENDPOINT: /api/schedule

# -- Schellar extra ENV
schellarExtraEnv: []

# -- PostgreSQL chart configuration
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: postgresU
    password: postgresP
    database: conductor
  architecture: standalone
  primary:
    initdb:
      scripts:
        init_db.sql: |
          CREATE DATABASE schellar;

  metrics:
    enabled: true
    image:
      repository: prometheuscommunity/postgres-exporter
      tag: latest

    serviceMonitor:
      enabled: true
      labels:
        prometheus: conductor-db

# -- Monitoring configuration
monitoring:
  enabled: true
  conductorPort: http-conductor
  conductorPath: /actuator/prometheus
  schellarPort: http-schellar
  schellarPath: /metrics

utilitiesImage:
  # -- utilities image repository
  repository: frinx/utilities-alpine
  # -- Overrides the image tag.
  tag: "1.2"
  # -- Image pull policy
  pullPolicy: IfNotPresent
