apiVersion: v2
name: frinx-machine-monitoring
description: A Helm chart for Kubernetes monitoring
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:

  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts/
    version: 60.0.0
    condition: kube-prometheus-stack.enabled

  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 2.16.0
    condition: loki.enabled

  - name: promtail
    repository: https://grafana.github.io/helm-charts
    version: 6.15.5
    condition: loki.enabled
