{{ if .Values.secrets.superuserSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{or .Values.name .Chart.Name}}-{{.Values.secrets.superuserSecret.name }}"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secrets.superuserSecret.username | b64enc | quote }}
  password: {{ .Values.secrets.superuserSecret.password | b64enc | quote }}
{{ end }}
