{{- if (include "cloud-native-pg.createPostInitSqlSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "cloud-native-pg.fullname" . }}-post-init-sql-secret
stringData:
  secret.sql: {{- required "Required value for secrets.postInitSqlSecret.sql" .Values.secrets.postInitSqlSecret.sql | toYaml | indent 1 }}
{{ end }}
