{{- if (include "cloud-native-pg.createUserSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloud-native-pg.fullname" . }}-frinx-user
type: kubernetes.io/basic-auth
data:
  username: {{ required "Required value for secrets.userSecret.username" .Values.secrets.userSecret.username | b64enc | quote }}
  password: {{ required "Required value for secrets.userSecret.password" .Values.secrets.userSecret.password | b64enc | quote }}
{{ end }}
