{{ if .Values.secrets.postInitSqlSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ or .Values.name .Chart.Name}}-{{.Values.secrets.postInitSqlSecret.name}}"
stringData:
  secret.sql: {{- .Values.secrets.postInitSqlSecret.sql | toYaml | indent 1 }}
{{ end }}
