{{ if .Values.secrets.userSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{or .Values.name .Chart.Name}}-{{.Values.secrets.userSecret.name}}"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secrets.userSecret.username | b64enc | quote }}
  password: {{ .Values.secrets.userSecret.password | b64enc | quote }}
{{ end }}
