{{- if (include "cloud-native-pg.createSuperuserSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloud-native-pg.fullname" . }}-frinx-superuser
type: kubernetes.io/basic-auth
data:
  username: {{ required "Required value for secrets.superuserSecret.username" .Values.secrets.superuserSecret.username | b64enc | quote }}
  password: {{ required "Required value for secrets.superuserSecret.password" .Values.secrets.superuserSecret.password | b64enc | quote }}
{{ end }}
