# # Default values for frinx-prometheus-config.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

# replicaCount: 1

kube-prometheus-stack:
  enabled: true

  fullnameOverride: "frinx-prometheus"

  grafana:
    enabled: false

  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'prometheus'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'krakend'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['krakend:9091']

        - job_name: 'conductor-server'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['conductor:8080']   

        - job_name: 'schellar'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['schellar:3000']     

        - job_name: 'uniconfig'
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ['uniconfig:8181']      

        - job_name: 'resource-manager'
          metrics_path: '/metrics'
          static_configs:
            - targets: ['resource-manager:8884']  

      serviceMonitorSelector:
        matchLabels:
          release: prometheus            

prometheus-postgres-exporter:
  enabled: true
  fullnameOverride: "frinx-postgres-exporter"

  service:
    labels:
      prometheus: monitoring

  config:
    datasource:
      host: 'uniconfig-postgresql'
      user: 'postgresU'
      password: 'postgresP'
      database: 'uniconfig'

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
    selector:
      matchLabels:
        prometheus: monitoring
    endpoints:
      - port: http
        interval: 30s
        scrapeTimeout: 10s  

  # prometheusRule:
  #   enabled: true
  #   additionalLabels: 
  #     release: prometheus
  #   rules: 
  #     - alert: PostgreSQLMaxConnectionsReached
  #       expr: sum by (server) (pg_stat_activity_count) >= sum by (server) (pg_settings_max_connections) - sum by (server) (pg_settings_superuser_reserved_connections)
  #       for: 5m
  #       labels:
  #         severity: critical
  #       annotations:
  #         description: '{{ "{{ $labels.server }}" }} is exceeding the currently configured maximum Postgres connection limit (current value: {{ `{{ $value }}` }}). Services may be degraded - please take immediate action (you probably need to increase max_connections in the Docker image and re-deploy.'
  #         summary: '{{ "{{ $labels.server }}" }} has maxed out Postgres connections.'

  #     - alert: PostgreSQLHighConnections
  #       expr: sum by (server) (pg_stat_activity_count) > (sum by (server) (pg_settings_max_connections) - sum by (server) (pg_settings_superuser_reserved_connections)) * 0.8
  #       for: 5m
  #       labels:
  #         severity: warning
  #       annotations:
  #         description: '{{ "{{ $labels.server }}" }} is exceeding 80% of the currently configured maximum Postgres connection limit (current value: {{ `{{ $value }}` }}). Please check utilization graphs and confirm if this is normal service growth, abuse or an otherwise temporary condition or if new resources need to be provisioned (or the limits increased, which is mostly likely).'
  #         summary: '{{ "{{ $labels.server }}" }} is over 80% of max Postgres connections.'

  #     - alert: PostgreSQLDown
  #       expr: pg_up != 1
  #       for: 5m
  #       labels:
  #         severity: critical
  #       annotations:
  #         description: '{{ `{{ $labels.instance }}` }} is rejecting query requests from the exporter, and thus probably not allowing DNS requests to work either. User services should not be effected provided at least 1 node is still alive.'
  #         summary: 'PostgreSQL is not processing queries: {{ `{{ $labels.instance }}` }}'
