{{- if (include "topology-discovery.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "topology-discovery.secretName" . }}
data:
  ARANGO_USERNAME: {{ .Values.dbPersistence.ARANGO_USERNAME | b64enc }}
  ARANGO_ROOT_PASSWORD: {{ .Values.dbPersistence.ARANGO_ROOT_PASSWORD | b64enc }}
{{- end -}}