apiVersion: v1
kind: Service
metadata:
  name: {{ include "topology-discovery.fullname" . }}
  labels:
    {{- include "topology-discovery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.kafkaClientPort }}
      targetPort: http-kafka
      protocol: TCP
      name: http-kafka-client
  selector:
    {{- include "topology-discovery.selectorLabels" . | nindent 4 }}
