apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-workflows.fullname" . }}
  labels:
    {{- include "demo-workflows.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demo-workflows.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-workflows.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: app-volume
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-workflows.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-uniconfig-ready
          image: curlimages/curl
          command: ["/bin/sh","-c"]
          args: ['while [ $(curl --insecure -o /dev/null --silent --write-out "%{http_code}" -X POST {{ .Values.env.UNICONFIG_HOSTNAME }}:{{ .Values.env.UNICONFIG_PORT }}/rests/operations/uniconfig-manager:health -H "Content-Type:application/json") -ne 200 ];
            do sleep 5; echo "waiting for uniconfig";
            done;
            echo "connection successful!"']
        - name: check-uniflow-ready
          image: curlimages/curl
          command: ["/bin/sh","-c"]
          args: ['while [ $(curl -o /dev/null --silent --write-out "%{http_code}" {{ .Values.env.UNIFLOW_HOSTNAME }}:{{ .Values.env.CONDUCTOR_PORT }}/health) -ne 200 ];
            do sleep 5; echo "waiting for uniflow";
            done;
            echo "connection successful!"']
        - name: check-inventory-ready
          image: curlimages/curl
          command: ["/bin/sh","-c"]
          args: ['while [ $(curl -o /dev/null --silent --write-out "%{http_code}" {{ .Values.env.INVENTORY_HOSTNAME }}:{{ .Values.env.INVENTORY_PORT }}/.well-known/apollo/server-health) -ne 200 ];
            do sleep 5; echo "waiting for inventory";
            done;
            echo "connection successful!"']        
        - name: copy-worker-files
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - '-c'
            - 'cp -r /home/app/* /tmp/app/'
          volumeMounts:
            - name: app-volume
              mountPath: /tmp/app/
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "UNICONFIG_URL_BASE"
              value: "http://{{ .Values.env.UNICONFIG_HOSTNAME }}:{{ .Values.env.UNICONFIG_PORT }}/rests"
            - name: "CONDUCTOR_URL_BASE"
              value: "http://{{ .Values.env.UNIFLOW_HOSTNAME }}:{{ .Values.env.UNIFLOW_PORT }}/proxy/api"
            - name: "INVENTORY_URL_BASE"
              value: "http://{{ .Values.env.INVENTORY_HOSTNAME }}:{{ .Values.env.INVENTORY_PORT }}/graphql"
            - name: "INSTANCES_TO_SIMULATE"
              value: {{ .Values.env.INSTANCES_TO_SIMULATE | quote }}
            - name: "RUN_TESTTOOLS"
              value: {{ .Values.env.RUN_TESTTOOLS | quote }}
            - name: "X_TENANT_ID"
              value: {{ .Values.env.X_TENANT_ID | quote }}
            - name: "X_AUTH_USER_GROUP"
              value: {{ .Values.env.X_AUTH_USER_GROUP | quote }}
          volumeMounts:
          - name: app-volume
            mountPath: /home/app
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
