apiVersion: v1
kind: Service
metadata:
  name: {{ include "swagger-ui.fullname" . }}
  labels:
    {{- include "swagger-ui.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "swagger-ui.selectorLabels" . | nindent 4 }}
