{{- if (include "inventory.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory.fullname" . }}
data:
  POSTGRES_USERNAME: {{ .Values.dbPersistence.POSTGRES_USERNAME | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.dbPersistence.POSTGRES_PASSWORD | b64enc }}
{{- end -}}
