apiVersion: v2
name: uniconfig
version: 5.0.0
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: traefik.enabled
    name: traefik
    repository: https://helm.traefik.io/traefik
    version: 20.8.0
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
appVersion: "5.1.4"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change traefik helm chart version to 20.8.0
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/215
    - kind: changed
      description: Set ingressClass in traefik-uniconfig
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/215
    - kind: added
      description: Add option to add labels into ingress resource
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/215
    - kind: removed
      description: Removed unused config file
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/215
