apiVersion: v2
name: uniconfig
version: 2.3.1
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: traefik.enabled
    name: traefik
    repository: https://helm.traefik.io/traefik
    version: 10.19.5
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
appVersion: "5.0.12"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update uniconfig image to 5.0.12
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/53
    - kind: fixed
      description: Fix namespaced rbac for traefik in local env
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/53
