apiVersion: v2
name: uniconfig
version: 8.1.0
appVersion: "6.1.1"
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: kafka.enabled
    name: kafka
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: FRINX
    email: services@frinx.io
    url: https://frinx.io
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added servicemonitor and monitoring configuration
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/397
