apiVersion: v2
name: uniconfig
version: 6.0.0
appVersion: "6.0.0"
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: traefik.enabled
    name: traefik
    repository: https://helm.traefik.io/traefik
    version: 26.1.0
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Changed ingress configuration
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/343
    - kind: changed
      description: Configuration of db connections via secrets
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/343
    - kind: changed
      description: Changed implementation of cache and mibs
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/343
    - kind: removed
      description: Removed AKS storage configuration
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/343
