apiVersion: v2
name: uniconfig
version: 2.3.0
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: traefik.enabled
    name: traefik
    repository: https://helm.traefik.io/traefik
    version: 10.19.5
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
appVersion: "5.0.9"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update uniconfig config files
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/45
    - kind: added
      description: Add tls_keystorePassword env variable
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/45
    - kind: fixed
      description: Fix _JAVA_OPTIONS variable value
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/45
    - kind: security
      description: Add capabilities
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/45
