apiVersion: v2
name: uniconfig
version: 2.0.1
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: traefik.enabled
    name: traefik
    repository: https://helm.traefik.io/traefik
    version: 10.19.5
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
appVersion: "5.0.5"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix loading of cache folder
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/30
    - kind: added
      description: Add extra Service option
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/30
