apiVersion: v2
name: uniconfig
version: 5.1.0
description: A Helm chart for UniConfig Kubernetes deployment
type: application
home: https://github.com/FRINXio/helm-charts
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: traefik.enabled
    name: traefik
    repository: https://helm.traefik.io/traefik
    version: 20.8.0
maintainers:
  - name: FRINX
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
appVersion: "5.1.4"
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix init-container permission
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/254
