apiVersion: v2
name: performance-monitor
description: FRINX Performance Monitor chart for FRINX-machine
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 2.0.0
appVersion: "7.0.1"
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
  - condition: kafka.enabled
    name: kafka
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: FRINX
    email: services@frinx.io
    url: https://frinx.io
annotations:
  artifacthub.io/images: |
    - name: performance-monitor
      image: frinx/performance-monitor:7.0.1
  artifacthub.io/changes: |
    - kind: changed
      description: update for 7.0 release
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/430
