apiVersion: v1
kind: Service
metadata:
  name: {{ include "frinx-frontend.fullname" . }}
  labels:
    {{- include "frinx-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portProxy }}
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
  selector:
    {{- include "frinx-frontend.selectorLabels" . | nindent 4 }}
