annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add option to add annotations to deployment
      links:
        - name: GitHub PR
          url: https://github.com/FRINXio/helm-charts/pull/174
apiVersion: v2
appVersion: "1.10"
dependencies:
- condition: sample-topology.enabled
  name: sample-topology
  repository: https://FRINXio.github.io/helm-charts
  version: 1.1.4
description: A Helm chart for the Frinx Machine demo workflows
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
maintainers:
- name: FRINX
name: demo-workflows
type: application
version: 1.3.0
