apiVersion: v2
name: demo-workflows
description: A Helm chart for the Frinx Machine demo workflows Kubernetes deployment
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 1.0.0
appVersion: "1.6.0"
maintainers:
  - name: FRINX
dependencies:
  - condition: sample-topology.enabled
    name: sample-topology
    repository: https://FRINXio.github.io/helm-charts
    version: 1.x.x
