apiVersion: v2
name: demo-workflows
description: A Helm chart for the Frinx Machine demo workflows
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 0.1.0
appVersion: "latest"
maintainers:
  - name: FRINX
dependencies:
  - condition: sample-topology.enabled
    name: sample-topology
    repository: https://FRINXio.github.io/helm-charts
    version: 1.x.x
