{{- if (include "workflow-manager.createSchellarSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow-manager.schellarSecretName" . }}
data:
  POSTGRES_USERNAME: {{ .Values.schellarDbPersistence.POSTGRES_USERNAME | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.schellarDbPersistence.POSTGRES_PASSWORD | b64enc }}
{{- end -}}
