{{- if (include "postgrest.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgrest.fullname" . }}
stringData:
  POSTGRES_USER: {{ .Values.database.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.database.postgresPassword }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.database.postgresUser .Values.database.postgresPassword .Values.database.postgresHostname ( .Values.database.postgresPort | toString ) .Values.database.postgresDb }}
{{- end -}}
