{{ if eq .Values.arangodb_config.enabled true }}
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
  {{- with .Values.arangodb_config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  mode: Single
  externalAccess:
    type: None
  bootstrap:
    passwordSecretNames:
      root: {{ .Values.arangodb_config.rootSecretName }}
  tls:
    caSecretName: None
  auth:
    jwtSecretName: {{ .Values.arangodb_config.tokenSecretName }}
  image: "{{ .Values.arangodb_config.image.repository }}:{{ .Values.arangodb_config.image.tag | default .Chart.AppVersion }}"
  single:
    securityContext:
      {{- toYaml .Values.arangodb_config.securityContext | nindent 6 }}
    resources:
      {{- toYaml .Values.arangodb_config.resources | nindent 6 }}
    affinity:
      {{- toYaml .Values.arangodb_config.affinity | nindent 6 }}
  id:
    securityContext:
      {{- toYaml .Values.arangodb_config.securityContext | nindent 6 }}
    resources:
      {{- toYaml .Values.arangodb_config.resources | nindent 6 }}
    affinity:
      {{- toYaml .Values.arangodb_config.affinity | nindent 6 }}
{{ end }}
