{{ if eq .Values.arangodb_config.enabled true }}
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  mode: Single
  tls:
    caSecretName: None
  auth:
    jwtSecretName: {{ .Values.arangodb_config.tokenSecretName }}
  image: "{{ .Values.arangodb_config.image.repository }}:{{ .Values.arangodb_config.image.tag | default .Chart.AppVersion }}"
{{ end }}
