# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.arangodb_config.tokenSecretName }}
type: "Opaque"
data:
  token: {{ default "" .Values.arangodb_config.token | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.arangodb_config.bearerSecretName }}
type: "Opaque"
data:
  token: {{ default "" .Values.arangodb_config.bearer | b64enc | quote }}
