{{- if (include "resource-manager.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource-manager.fullname" . }}
data:
  POSTGRES_USERNAME: {{ .Values.dbPersistence.POSTGRES_USERNAME | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.dbPersistence.POSTGRES_PASSWORD | b64enc }}
{{- end -}}
