name: Build Custom Python Image

on:
  push:
    branches:
      - main
    paths:
      - '.github/dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/dockerfile'
  workflow_dispatch:

env:
  IMAGE_PREFIX: frinx
  IMAGE_BASE_NAME: python-pyyaml
  IMAGE_BASE_MAJOR_VERSION: 3
  IMAGE_BASE_MINOR_VERSION: 12.41

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ IMAGE_PREFIX/$IMAGE_BASE_NAME }}:${{ IMAGE_BASE_MAJOR_VERSION.$IMAGE_BASE_MINOR_VERSION }}" -f .github/dockerfile .

      - name: Push Docker image
        run: docker push "${{ IMAGE_PREFIX/$IMAGE_BASE_NAME }}:${{ IMAGE_BASE_MAJOR_VERSION.$IMAGE_BASE_MINOR_VERSION }}"
