name: Lint and Test Frinx-machine

on:
  pull_request:
    paths:
      - 'charts/frinx-machine/**'

jobs:
  lint-test-frinx-machine:
    runs-on:
      - self-hosted
      - frinx-internal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Helm tool installer
        uses: Azure/setup-helm@v3.3
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/frinx-machine_lint_test_config.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      # - name: Run chart-testing (lint)
      #   run: ct lint --config .github/frinx-machine_lint_test_config.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --config .github/frinx-machine_lint_test_config.yaml
      
      - name: Install cert-manager helm-chart
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm install cert-manager jetstack/cert-manager

      - name: Install testkube helm-chart
        run: |
          helm repo add testkube https://kubeshop.github.io/helm-charts
          helm install --namespace default testkube testkube/testkube --wait

      - name: Install helm-chart for e2e tests
        run: |
          helm dependency update charts/frinx-machine
          helm install frinx-dev charts/frinx-machine --wait --timeout 20m0s

      # Creating test
      - name: Create test
        id: create_test
        uses: kubeshop/testkube-docker-action@v1
        with:
          command: create
          resource: test
          namespace: testkube
          parameters: "--git-uri https://github.com/FRINXio/frinx-machine-e2e-tests.git --git-branch main --name frinx-e2e --type cypress/project"
        env:
          KUBERNETES_MASTER: /home/frinx/.kube/config

      # Running test
      - name: Run test
        id: run_test
        uses: kubeshop/testkube-docker-action@v1
        with:
          command: run
          resource: test
          parameters: "frinx-e2e"
        env:
          KUBERNETES_MASTER: /home/frinx/.kube/config
