name: Lint and Test Frinx-machine

on:
  pull_request:
    paths:
      - 'charts/frinx-machine/**'

jobs:
  lint-test-frinx-machine-chart:
    runs-on: ubuntu-22.04
    timeout-minutes: 50
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ahmadnassri/action-workflow-queue@v1

      - name: Helm tool installer
        uses: Azure/setup-helm@v3.3
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/frinx-machine_lint_test_config.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      # - name: Run chart-testing (lint)
      #   run: ct lint --config .github/frinx-machine_lint_test_config.yaml

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Create AKS cluster
      #   run: |
      #     az aks create --resource-group github-e2e-tests --name aks-e2e-tests --node-count 1 --node-vm-size standard_e4as_v4 --generate-ssh-keys

      - uses: azure/aks-set-context@v3
        with:
           resource-group: 'github-e2e-tests'
           cluster-name: 'aks-e2e-tests'
      
      # - name: Run chart-testing (install)
      #   run: ct install --config .github/frinx-machine_lint_test_config.yaml      

      - name: Install testkube plugin
        run: |
          wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add -
          echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y testkube

      # - name: Install cert-manager helm-chart
      #   run: |
      #     kubectl create namespace cert-manager
      #     kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
      #     helm repo add jetstack https://charts.jetstack.io
      #     helm install my-release --namespace cert-manager --version v1.9.1 jetstack/cert-manager

      # # Install testkube
      # - name: Install testkube
      #   id: install_testkube
      #   run: |
      #     helm repo add testkube https://kubeshop.github.io/helm-charts
      #     helm install --create-namespace --namespace testkube --version 1.4.5 testkube testkube/testkube --wait

      # - name: Install helm-chart for e2e tests
      #   run: |
      #     helm dependency update charts/frinx-machine
      #     helm install frinx-dev charts/frinx-machine --set demo-workflows.enabled=true -n frinx-e2e --create-namespace --wait --timeout 20m0s

      # Creating e2e tests
      - name: Create test
        id: create_test
        run: |
          kubectl testkube create test --git-uri https://github.com/FRINXio/frinx-machine-e2e-tests.git --git-branch main --name frinx-e2e --type cypress/project

      # Running e2e tests
      - name: Run test
        id: run_test
        run: |
          kubectl testkube run test frinx-e2e -f

      - name: Download artifacts
        if: ${{ failure() }}
        id: download_artifacts
        run: |
          echo "$(kubectl testkube get executions | sed -n '4p' | cut -d " " -f3)" >> $EXECUTION_ID
          kubectl testkube download artifacts $EXECUTION_ID
          ls

      - name: Download variables from merge workflow
        if: ${{ failure() }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: frinx-machine-lint-test.yaml
          name: artifacts
          path: ${{ github.workspace }}/artifacts

      # - name: Delete AKS cluster
      #   if: ${{ always() }}
      #   run: |
      #     az aks delete --resource-group github-e2e-tests --name aks-e2e-tests --yes

      - name: slack - GitHub Actions Slack integration
        if: ${{ always() }}
        uses: act10ns/slack@v1.6.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          channel: '#helm-charts'
          message: "E2E tests: ${{ job.status }}\n${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
