name: Lint frinx-machine chart

on:
  pull_request:
    paths:
      - 'charts/frinx-machine/**'

jobs:
  lint-frinx-machine-chart:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: v3.9.0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/frinx-machine_lint_test_config.yaml
